- lib/commands/debug.ts
- lib/declarations.d.ts
- lib/project.ts
- lib/services/build.ts
Implement platform-specific .abignore files
Refs http://teampulse.telerik.com/view#item/281060
> Implement platform-specific .abignore files

- lib/commands/simulate.ts
Fixes http://teampulse.telerik.com/view#item/283107
> Fix simulate command

- lib/services/cordova-plugins.ts
Fixes http://teampulse.telerik.com/view#item/281349
> Ensure that plugin commands work only on Cordova projects

- README.md
Adding Internet Explorer sys req
> Fixing Node.js sys reqs

- resources/default-project-cordova.json
- test/resources/blank-cordova.abproject
They should come from the templates instead.
Fixes http://teampulse.telerik.com/view#item/283210
> Remove default Cordova plugins & variables

- resources/help.txt
http://teampulse.telerik.com/view#item/262237
> Support for WP8 Ion

- lib/commands/emulate.ts
Also gives a proper message to the user
Implements http://teampulse.telerik.com/view#item/279833
> Android Emulator now checks whether the SDK is correctly configured

- lib/login.ts
- lib/services/user-settings-service.ts
See http://teampulse.telerik.com/view#item/283384
> Store user data & login cookie per-environment

- lib/commands/cryptographic-identities.ts
Fixes http://teampulse.telerik.com/view#item/283398
> Don't fail if the request to "http://freegeoip.net/json/" is not successful

- lib/commands/itunes-connect.ts
- lib/service-util.ts
http://teampulse.telerik.com/view#item/283456
> Print the correct server error message when 402 is returned

- lib/services/plugins-service.ts
http://teampulse.telerik.com/view#item/283256
> Add plugin by identifier

- lib/services/build.ts
http://teampulse.telerik.com/view#item/283537
> Fixing build

- lib/commands/simulate.ts
http://teampulse.telerik.com/view#item/283542
> Fixing windows simulator

- resources/help.txt
Update package.json to use telerik fork of winreg module (currently it points to vladimirov/specify-registry-version branch). Update common lib.
http://teampulse.telerik.com/view#item/274611
> Use genymotion

- lib/services/build.ts
Add "dots printing" when building a project. This way the user will know something is still working. The output will look like this:
$ appbuilder build android
Building project for platform 'Android', configuration 'Debug'
Building project buildProgressIndicator/buildProgressIndicator (Private_Build_Folder)
Building...............
Build log written to 'D:\AppBuilder_Projects\buildProgressIndicator\.ab\build.log'
On each 2 seconds a new dot will appear.
Update common lib, where a new function (printMsgWithTimeout) has been added.
http://teampulse.telerik.com/view#item/278000
> Add progress indication when building a project

- lib/commands/appmanager.ts
- lib/commands/deploy.ts
- resources/help.txt
See http://teampulse.telerik.com/view#item/283182
> The help says that one can publish NativeScript projects to AppManager

- lib/services/build.ts
Improve message shown when you have to scan QR code in order to deploy to appbuilder companion app.
> Improve message when deploying to Ion

- README.md
- lib/commands/cryptographic-identities.ts
- lib/project/cordova-project.ts
- lib/services/project-simulator-service.ts
- package.json
- resources/default-project-cordova.json
- resources/help.txt
- test/resources/blank-cordova.abproject
Merge branch 'release' into vladimirov/merge-release-in-master-2-7-0
Conflicts to be checked:
lib/commands/simulate.ts
lib/services/build.ts
package.json
resources/help.txt
> Merge release branch into master

- .gitignore
- config/config.json
- lib/bootstrap.ts
- lib/commands/dev/config.ts
- lib/config.ts
- lib/declarations.d.ts
* Revert config.json
* Gitignore config.json
* Add dev-config command that prints current config data
* Ensure that config file exists after clean clone of the repository
> gitignore config.json file

- lib/commands/update-kendoui.ts
- lib/declarations.d.ts
- package.json
Also, pretty-print all the information in a nicely drawn table.
implements http://teampulse.telerik.com/view#item/283189
> Print "verified" tag when updating Kendo UI

- package.json
> Update version to 2.7.2

- lib/commands/itunes-connect.ts
implements http://teampulse.telerik.com/view#item/280886
> Pretty-print iTunes connect application info for appstore list command

- README.md
NOTE: Not merging until the release date. Hopefully, we won't need to fix it.
> Prepping for the update release

- lib/config.ts
- lib/project.ts
see http://teampulse.telerik.com/view#item/282660
> Pretty-print written json files

- README.md
- package.json
Merge branch 'release' into vladimirov/merge-release-in-master-2-7-2
Conflicts:
lib/services/build.ts
> Merge release in master - 2.7.2

- README.md
- package.json
- resources/project-properties-nativescript.json
- test/resources/blank-NativeScript.abproject
Merge release in master after 2.7.3
> Merge release in master after 2.7.3

- lib/commands/project.ts
- lib/project.ts
- lib/project/project.d.ts
Add initializeProjectFromExistingFiles method that creates .abproject files and extracts .debug.abproject, .release.abproject and .abignore files from Blank template. If any of the files already exists, it will not be overwritten.
http://teampulse.telerik.com/view#item/284263
> Init command to extract .*.abproject and .abignore

- lib/project.ts
- lib/project/cordova-project.ts
- lib/project/framework-project-base.ts
- lib/project/nativescript-project.ts
- lib/project/project.d.ts
- lib/project/resolvers/framework-project-resolver-base.ts
- lib/project/resolvers/framework-project-resolver.ts
- lib/project/web-site-project.ts
- lib/services/project-properties-service.ts
- lib/templates-service.ts
- test/project.ts
Should be merged after this https://github.com/telerik/mobile-cli-lib/pull/146
> Prepare correct list of corePlugins

- lib/bootstrap.ts
- lib/commands/plugin/find-plugins.ts
- lib/declarations.d.ts
- lib/services/cordova-plugins.ts
The root of this problem resides in
plugman's search function line 29 in ~/lib/services/cordova-plugins.ts
It doesn't really return IPlugin so a new interface is required
Related to http://teampulse.telerik.com/view#item/284370
Ping @rosen-vladimirov @Fatme @teobugslayer
> Fix plugin find command

- lib/project.ts
http://teampulse.telerik.com/view#item/284648
> Fix cordova migration

- lib/project.ts
http://teampulse.telerik.com/view#item/284263
> Fixes the exception that is thrown when initializing project in empty directory

- lib/commands/plugin/fetch-plugin.ts
Fixes http://teampulse.telerik.com/view#item/284717
Ping @rosen-vladimirov @Fatme @teobugslayer
> Fix plugin fetch command

- lib/bootstrap.ts
- lib/project/cordova-project.ts
- lib/project/nativescript-project.ts
- lib/services/build.ts
http://teampulse.telerik.com/view#item/284767
> Don't allow wp8 builds for nativescript projects

- lib/definitions/osenv.d.ts
Should be merged after this https://github.com/telerik/mobile-cli-lib/pull/155
> Move osenv to common

- package.json
- test/path-filtering.ts
See http://teampulse.telerik.com/view#item/284931
> Update minimatch to the latest version

- package.json
Set version to 2.8.0 in order to prepare for the new release.
> Set version to 2.8.0

- lib/bootstrap.ts
- lib/services/project-simulator-service.ts
Fixes http://teampulse.telerik.com/view#item/284867
> Fix simulate command for website project

- lib/declarations.d.ts
- lib/project/project-files-manager.ts
- lib/services/path-filtering.ts
- test/stubs.ts
See http://teampulse.telerik.com/view#item/278125
> LiveSync over cable consults .abignore

- lib/commands/live-sync.ts
Keep all changes and hit the device every 500 ms
See http://teampulse.telerik.com/view#item/285009
> Batch LiveSync over cable

- lib/commands/cryptographic-identities.ts
Those come from Apple and don't have a password
Fixes http://teampulse.telerik.com/view#item/273404
Ping @rosen-vladimirov @Fatme @teobugslayer
> Remove password prompt when uploading .cer certificate

- README.md
> New Linux reqs

- lib/commands/project.ts
Add message that project has been successfully initialize after calling '$ appbuilder init' or '$ appbuilder init hybrid'. Successfully initialized %s project. (%s being Cordova, NativeScript or MobileWebsite).
http://teampulse.telerik.com/view#item/285141
> Improve output of init command

- lib/commands/emulate.ts
- lib/services/build.ts
Fixes http://teampulse.telerik.com/view#item/285220
> Respect options.release from emulate command

- ABIGNORE.md
- README.md
- lib/commands/debug.ts
- lib/commands/edit-configuration.ts
- lib/commands/emulate.ts
- lib/commands/project.ts
- lib/commands/simulate.ts
- lib/host-info.ts
- lib/options.ts
- lib/project.ts
- lib/services/build.ts
- lib/services/multipart-upload.ts
- lib/services/project-properties-service.ts
- resources/help.txt
- test/project.ts
- test/resources/blank-NativeScript.abproject
Merge all current changes from release in master.
> Merge release in master before 2.8.0

- package.json
Fixes http://teampulse.telerik.com/view#item/283764
Should be merged after this PR https://github.com/telerik/mobile-cli-lib/pull/168
> Fix run command

- lib/config.ts
- lib/declarations.d.ts
- lib/project.ts
- lib/project/project-constants.ts
- lib/project/project.d.ts
- lib/services/plugins-service.ts
- test/stubs.ts
Fixes http://teampulse.telerik.com/view#item/282804
> Create config files if options.debug or options.release are set

- lib/plugins-data.ts
- lib/project/project-constants.ts
- lib/project/project.d.ts
- lib/services/cordova-plugins.ts
- lib/services/marketplace-plugins-service.ts
- test/plugins-service.ts
Fixes http://teampulse.telerik.com/view#item/281723
> Print plugin variables value's when executing appbuilder plugin

- lib/project.ts
Improve messages when migrating WPSdk and FrameworkVersion.
> Improve messages

- lib/services/build.ts
Fixes http://teampulse.telerik.com/view#item/285544
> Download ipa if an AppStore provision is selected

- lib/services/samples-service.ts
Fixes http://teampulse.telerik.com/view#item/285822
> Remove chrome samples from sample list

- resources/help.txt
http://teampulse.telerik.com/view#item/284307
> Help for timeout option passed to emulate and remote commands

- lib/project.ts
Fixes http://teampulse.telerik.com/view#item/285465
Related to https://github.com/telerik/mobile-cli-lib/pull/187
> Fix case-sensitivity error when creating project from template

- README.md
Not merging until we're certain of the release date
> AB28 release dates:

- lib/commands/cryptographic-identities.ts
Fixes http://teampulse.telerik.com/view#item/286130
> Fix identifies autoselect

- package.json
Set version to 2.8.1, so we can release the hotfix.
> Set version to 2.8.1

- lib/services/project-properties-service.ts
- test/file-system.ts
- test/project-properties-service.ts
- test/project.ts
- test/stubs.ts
- Add projectVersion autocompletion tests.
- Add WPSdk tests
- Add unzip tests - overwriteExistingFiles option and fix issue with usage
- Add unzip tests - caseSensitive option and fix usage
- Add init command tests - validate all config and mandatory files exists after init
> Add unit tests

- README.md
- package.json
- resources/help.txt
Merge release in master (for 2.8.1)
> Merge release in master (for 2.8.1)

- lib/commands/deploy.ts
- lib/project.ts
- lib/project/project-constants.ts
- lib/project/project.d.ts
- lib/services/build.ts
Fixes http://teampulse.telerik.com/view#item/286588
> Respect appIdentifier from info.plist file when iOSDeploymentValidator is executed

- lib/commands/deploy.ts
- lib/declarations.d.ts
- lib/project.ts
- lib/project/cordova-project.ts
- lib/project/nativescript-project.ts
- lib/project/project-constants.ts
- lib/project/project-files-manager.ts
- lib/project/project.d.ts
- lib/services/build.ts
- lib/services/project-properties-service.ts
- package.json
- resources/json-schemas/WP.json
- test/edit-configuration.ts
- test/resources/blank-Cordova.abproject
Merge branch 'release' into vladimirov/merge-release-2-8-2
Update common lib to latest version
Conflicts:
lib/services/build.ts
test/edit-configuration.ts
> Merge release branch from 2.8.2

- test/resources/blank-NativeScript.abproject
Use correct nativescript version.
I'll fix these tests in master branch to work correctly instead of fixing them before each release.
> Fix nativescript project version in tests

- bin/appbuilder
Related to http://teampulse.telerik.com/view#item/287068
> Fix Bash passing unescaped arguments to node

- lib/commands/cryptographic-identities.ts
Related to http://teampulse.telerik.com/view#item/285750
> Add multiple password prompt when importing p12 keys

- Gruntfile.js
Merge gruntfile fix, that has been applied in release branch AFTER 2.8.2 had been released.
> Merge gruntfile fix from release branch

- package.json
> Set version to 2.8.3

- lib/services/samples-service.ts
- package.json
1. Get information from all pages when reading data from GitHub
2. changed regex to accommodate for the mobile website template
3. fixed unzipping on node 0.12 under windows (a common lib change)
4. small speedups
5. updated byline to remove warning on install
> Fix hidden mobile website sample

- resources/help.txt
Remove help that is invalid for deploy android command.
> Fix error in help.txt

- lib/commands/remote.ts
- lib/declarations.d.ts
- lib/login.ts
- lib/service-util.ts
- lib/services/livesync-service.ts
- lib/services/multipart-upload.ts
- test/multipart-upload.ts
- test/stubs.ts
> Update to Node 0.12 definitions

- README.md
- lib/project/cordova-project.ts
- lib/project/nativescript-project.ts
- package.json
- test/project.ts
- test/resources/blank-Cordova.abproject
Merge release in master (2.8.3)
> Merge release branch from 2.8.3 release

- postinstall.js
Implements http://teampulse.telerik.com/view#item/288230
> At install, ask the user to allow auto completion

- lib/services/livesync-service.ts
- lib/services/server-extensions.ts
- test/stubs.ts
Should be merged after this https://github.com/telerik/mobile-cli-lib/pull/244
> Remove enoent checks, use tryExecuteFileOperation function instead

- docs/man_pages/publishing/appstore-upload.md
- lib/commands/itunes-connect.ts
- lib/declarations.d.ts
- lib/project/cordova-project.ts
- lib/project/nativescript-project.ts
- lib/project/web-site-project.ts
Allow publishing of NS projects to iTunes Connect.
http://teampulse.telerik.com/view#item/286402
> Allow publishing of NS projects to iTunes

- lib/commands/livesync-cloud.ts
- lib/declarations.d.ts
- lib/project.ts
- lib/project/project.d.ts
- lib/services/build.ts
- test/build-configurations.ts
- test/project.ts
Move some inappropriate code from the build service
to the project service, along with all dependencies.
Ping @Fatme @rosen-vladimirov
> Refactor build and project services

- resources/typescript-definitions-files/declarations.d.ts
Update the file in our resources which is used for TypeScript projects. Set the return value of setTimeout and setInterval to any in order to support cases when it returns number and Timer. Add setImmediate and clearImmediate methods.
> Update typescript declarations file

- test/resources/blank-Cordova.abproject
- test/resources/blank-NativeScript.abproject
The templates were changed on the server and we need to update our test templates.
> Fix broken integration tests

- lib/commands/plugin/add-plugin.ts
- lib/commands/plugin/list-plugin.ts
- lib/declarations.d.ts
- lib/plugins-data.ts
- lib/server-api.d.ts
- lib/server-api.ts
- lib/services/cordova-plugins.ts
- lib/services/marketplace-plugins-service.ts
- lib/services/plugins-service.ts
- test/build-configurations.ts
- test/plugins-service.ts
http://teampulse.telerik.com/view#item/279691
> Marketplace versioning

- lib/server-api.d.ts
- lib/server-api.ts
- lib/services/marketplace-plugins-service.ts
- lib/services/plugins-service.ts
http://teampulse.telerik.com/view#item/289686
> Use latest server api

- Gruntfile.js
It now compiles and runs all tests
> Fix 'grunt test' task

- test/project.ts
- test/stubs.ts
So that our mocks correctly implement the interface
> Add IPrompter methods to unit test stubs

- test/project.ts
- test/stubs.ts
Fixes http://teampulse.telerik.com/view#item/289843
> Start WP8 Emulator on 64 bit node

- docs/man_pages/project/testing/livesync.md
> Fix livesync help

- lib/commands/project/create-project.ts
- lib/commands/project/create.ts
- lib/commands/project/project-command-base.ts
http://teampulse.telerik.com/view#item/290014
> Throw error if the specified project directory is part of existing project

- package.json
The following improvements are included:
* Update marked-terminal to latest version, which supports nested lists.
In common lib:
* Make the logo of the CLI in HTML Help a link to index.html page.
* In console help replace `&nbsp;` with space.
* In console help replace all links with their text.
* In console help remove the inner borders of cli-tables.
Fixes http://teampulse.telerik.com/view#item/290011
Implements http://teampulse.telerik.com/view#item/290045
> Improve help service

- package.json
> Use info-zip based unzip on windows, and OS supplied one on linux

- lib/commands/project/create.ts
- lib/services/screen-builder-service.ts
http://teampulse.telerik.com/view#item/290013
> Don't use globally installed bower when creating sb project

- package.json
Set version in package.json to 2.9.0
> Set version to 2.9.0

- test/common-errors.ts
- test/common-helpers.ts
Includes **renaming** of *common-errors.ts* previously incorrectly named *common-helpers.ts*
> Add unit tests for remove<T> in common/helpers

- AppBuilderCLI.njsproj
- docs/man_pages/publishing/publish-add.md
- docs/man_pages/publishing/publish-remove.md
- docs/man_pages/publishing/publish.md
- lib/bootstrap.ts
- lib/commands/publish.ts
- lib/declarations.d.ts
- lib/options.ts
- lib/project.ts
- lib/project/cordova-project.ts
- lib/project/nativescript-project.ts
- lib/project/project-files-manager.ts
- lib/project/project.d.ts
- lib/project/web-site-project.ts
- lib/server-api.d.ts
- lib/server-api.ts
- lib/services/plugins-service.ts
- lib/services/publish-service.ts
- test/stubs.ts
It enables publishing a **website** to a remote **ftp** server
Merge **after** https://github.com/telerik/mobile-cli-lib/pull/276 and https://github.com/Icenium/Ice/pull/3378 
Related to http://teampulse.telerik.com/view#item/286459
> Add publish command

- lib/services/publish-service.ts
Fixes http://teampulse.telerik.com/view#item/290174
> Reword publish command help text

- lib/commands/cloud-projects.ts
Fixes http://teampulse.telerik.com/view#item/289508
> Refuse to cloud export into existing project sub-dir

- docs/man_pages/project/creation/cloud-export.md
- docs/man_pages/project/creation/cloud.md
- docs/man_pages/project/creation/create-hybrid.md
- docs/man_pages/project/creation/create-native.md
- docs/man_pages/project/creation/create-screenbuilder.md
- docs/man_pages/project/creation/create-website.md
- docs/man_pages/project/creation/init-hybrid.md
- docs/man_pages/project/creation/init-native.md
- docs/man_pages/project/creation/init-website.md
- docs/man_pages/project/creation/init.md
- docs/man_pages/project/creation/sample-clone.md
- docs/man_pages/project/creation/sample-hybrid.md
- docs/man_pages/project/creation/sample-native.md
- docs/man_pages/project/creation/sample-website.md
- docs/man_pages/project/creation/sample.md
- lib/bootstrap.ts
- lib/commands/project/create.ts
http://teampulse.telerik.com/view#item/290019
Retarget https://github.com/Icenium/icenium-cli/pull/925
> Add screenbuilder type to create command

- lib/commands/project/create-project.ts
- lib/commands/project/create.ts
- lib/commands/project/name-command-parameter.ts
- lib/commands/project/project-command-base.ts
- test/project-name-validator.ts
- test/project.ts
Along with some unit/integration tests
Fixes http://teampulse.telerik.com/view#item/290072
Merge after https://github.com/telerik/mobile-cli-lib/pull/292
> Fix no error when project name is too long

- docs/man_pages/publishing/publish.md
Related to 
http://teampulse.telerik.com/view#item/286459
> Add `publish remove` to related commands in the HTML help

- lib/json-schema/json-schema-validator.ts
- lib/json-schema/json-schema.d.ts
- lib/project.ts
- lib/project/cordova-project.ts
- lib/project/project-constants.ts
- lib/project/project.d.ts
- lib/services/build.ts
- test/build-configurations.ts
- test/stubs.ts
http://teampulse.telerik.com/view#item/289832
> Validate with platform specific schemas on build

- lib/services/dependency-extensions-service-base.ts
- lib/services/extensions-service-base.ts
http://teampulse.telerik.com/view#item/290449
> Fix progress indicator

- lib/commands/plugin/add-plugin.ts
- lib/commands/plugin/list-plugin.ts
- lib/services/plugins-service.ts
http://teampulse.telerik.com/view#item/290041
http://teampulse.telerik.com/view#item/290159
http://teampulse.telerik.com/view#item/290038
> marketplace plugins fixes

- docs/man_pages/screenbuilder/add-dataprovider.md
- docs/man_pages/screenbuilder/add-field.md
- docs/man_pages/screenbuilder/add-form.md
- docs/man_pages/screenbuilder/add-list.md
- docs/man_pages/screenbuilder/add-signin.md
- docs/man_pages/screenbuilder/add-signup.md
- docs/man_pages/screenbuilder/add-view.md
- docs/man_pages/screenbuilder/screenbuilder.md
http://teampulse.telerik.com/view#item/290499
> Fix wrong url

- lib/services/build.ts
Fixes http://teampulse.telerik.com/view#item/290175
> Fix confusing message when attempting to build websites

- lib/services/screen-builder-service.ts
http://teampulse.telerik.com/view#item/290473
> FIx --path option for sb projects

- package.json
Use cli-table from v0.3.1.0 tag in Telerik's fork.
> Use cli-table from tag

- lib/commands/project/create.ts
- lib/project.ts
http://teampulse.telerik.com/view#item/290832
> Improve error message

- lib/commands/simulate.ts
- lib/services/dependency-extensions-service-base.ts
- lib/services/extensions-service-base.ts
- lib/services/server-extensions.ts
http://teampulse.telerik.com/view#item/290997
> Don't save extension-versions file if the preparing of sb fails

- package.json
Update cli-table version to latest tag - v.0.3.1.1
In this version there's additional fix for http://teampulse.telerik.com/view#item/291100
> Use latest cli-table

- lib/commands/project/init.ts
http://teampulse.telerik.com/view#item/291121
> Fix init command

- docs/man_pages/project/creation/create.md
- docs/man_pages/screenbuilder/add-dataprovider.md
- docs/man_pages/screenbuilder/add-field.md
- docs/man_pages/screenbuilder/add-form.md
- docs/man_pages/screenbuilder/add-list.md
- docs/man_pages/screenbuilder/add-signin.md
- docs/man_pages/screenbuilder/add-signup.md
- docs/man_pages/screenbuilder/add-view.md
- docs/man_pages/screenbuilder/screenbuilder.md
- lib/commands/project/create.ts
- lib/commands/project/init.ts
- lib/commands/samples.ts
- lib/commands/simulate.ts
- lib/config.ts
- lib/declarations.d.ts
- lib/project.ts
- lib/project/project.d.ts
- lib/services/build.ts
- lib/services/dependency-extensions-service-base.ts
- lib/services/extensions-service-base.ts
- lib/services/screen-builder-service.ts
- lib/services/server-extensions.ts
- package.json
- test/commands-service.ts
> Merge 2.9.1 in master

- lib/project.ts
- lib/project/framework-project-base.ts
This way if some of them are missing, regardless whether optional or mandatory, they will be procured.
Fixes http://teampulse.telerik.com/view#item/290864
> Ensure all assets are present when migrating cordova project

- lib/plugins-data.ts
http://teampulse.telerik.com/view#item/286725
> Getting marketplace plugin identifier from MarketPlaceVersionsData

- lib/services/publish-service.ts
Stop relying on the server's message and just print the error
Addresses http://teampulse.telerik.com/view#item/290471
Depends on https://github.com/Icenium/Ice/pull/3611
> Provide better error handling in CLI

- lib/project.ts
Fixes http://teampulse.telerik.com/view#item/291262
> Rollback properly upon cordova migration failure

- resources/typescript-definitions-files/ios.d.ts
Depends on https://github.com/telerik/mobile-cli-lib/pull/327
> Fix hierarchical commands' case-sensitivity

- test/cryptographic-identities.ts
Implements http://teampulse.telerik.com/view#item/266466
> Add unit tests for ios provision/certificate autoselection

- README.md
Note: Don't merge this until we're certain of the release dates.
> Updated version and release date in the readme for 2.9.1

- README.md
- lib/plugins-data.ts
- package.json
Merge 2.9.1 changes in master and update to latest common lib.
> Merge 2.9.1 changes in master

- config/dependency-config.json
- docs/man_pages/project/creation/create-screenbuilder.md
- docs/man_pages/screenbuilder/add-about.md
- docs/man_pages/screenbuilder/add-dataprovider.md
- docs/man_pages/screenbuilder/add-field.md
- docs/man_pages/screenbuilder/add-list.md
- docs/man_pages/screenbuilder/add-signin.md
- docs/man_pages/screenbuilder/add-signup.md
- docs/man_pages/screenbuilder/add-view.md
- docs/man_pages/screenbuilder/screenbuilder.md
http://teampulse.telerik.com/view#item/291564
> Update sb version

- package.json
> Set version to 2.9.2

- lib/services/appmanager-service.ts
- package.json
Merge release branch in master, pre 2.9.2
Conflicts:
lib/services/appmanager-service.ts
> Merge release branch in master, pre 2.9.2

- README.md
> Merge 2.9.2 in master

- README.md
Set release date of 2.9.2 to May 20
> Set release date of 2.9.2 to May 20

- docs/man_pages/publishing/appmanager-groups.md
- docs/man_pages/publishing/appmanager-livesync.md
- docs/man_pages/publishing/appmanager-upload-android.md
- docs/man_pages/publishing/appmanager-upload-ios.md
- docs/man_pages/publishing/appmanager-upload-wp8.md
- docs/man_pages/publishing/appmanager-upload.md
- docs/man_pages/publishing/appmanager.md
- docs/man_pages/publishing/appstore-list.md
- docs/man_pages/publishing/appstore-upload.md
- docs/man_pages/publishing/appstore.md
- docs/man_pages/publishing/certificate-export.md
- docs/man_pages/publishing/certificate-import.md
- docs/man_pages/publishing/certificate-remove.md
- docs/man_pages/publishing/certificate-request-create.md
- docs/man_pages/publishing/certificate-request-download.md
- docs/man_pages/publishing/certificate-request-remove.md
- docs/man_pages/publishing/certificate-request.md
- docs/man_pages/publishing/certificate.md
- docs/man_pages/publishing/provision-import.md
- docs/man_pages/publishing/provision-remove.md
- docs/man_pages/publishing/provision.md
- lib/bootstrap.ts
- lib/commands/appmanager.ts
- lib/declarations.d.ts
- lib/options.ts
- lib/server-api.d.ts
- lib/server-api.ts
- lib/services/appmanager-service.ts
Implements http://tpdogfood.telerik.com/View#item/157843
> Add support for direct app publishing and group assigning

- README.md
- test/resources/blank-NativeScript.abproject
> Merge latest 2.9.2 commits

- lib/project.ts
- lib/project/cordova-project.ts
- lib/project/nativescript-project.ts
- lib/project/project.d.ts
- lib/project/web-site-project.ts
- lib/services/build.ts
- test/project-properties-service.ts
- test/stubs.ts
Implements http://teampulse.telerik.com/view#item/290757
Merge after https://github.com/telerik/mobile-cli-lib/pull/339
> Allow iOS build to look through all provision types

- package.json
> Set version to 2.9.3

- README.md
- package.json
> Merge 2.9.3

- config/dependency-config.json
- lib/services/app-scaffolding-extensions-service.ts
http://teampulse.telerik.com/view#item/291564
> Update sb to 0.0.7

- lib/commands/cryptographic-identities.ts
Also do not prompt for password when importing .cer file
Fixes http://teampulse.telerik.com/view#item/292671
Merge along with https://github.com/telerik/mobile-cli-lib/pull/348
> Fix weird error message when importing certificate with no password

- lib/services/build.ts
If a **valid** AdHoc provision is present it should be chosen with priority over the others (due to the fact that it can generate a QR code)
Fixes http://teampulse.telerik.com/view#item/292411
> Use AdHoc provision first if possible

- lib/services/cordova-migration-service.ts
- lib/services/cordova-plugins.ts
- test/plugins-service.ts
http://teampulse.telerik.com/view#item/292500
> Detect Core plugins using the RegEx in cordova.json

- package.json
> Set version to 2.10

- lib/commands/debug.ts
http://teampulse.telerik.com/view#item/292771
Should be merged after this PR https://github.com/Icenium/Ice/pull/3762
> Fix debugging of NativeScript applications

- lib/declarations.d.ts
- lib/server-config.ts
- lib/services/cordova-migration-service.ts
- test/cordova-migration-service.ts
- test/project.ts
Fixes http://teampulse.telerik.com/view#item/292884
> Enable AndroidHardwareAcceleration when migrating to Cordova version greater than 4.0.0

- lib/services/plugins-service.ts
When user executes **$ appbuilder plugin add com.telerik.LivePatch** we automatically add it to both debug and release configurations. This plugin cannot work with LiveSync plugin enabled in debug mode, so we should enable LivePatch only for release.
Fixes http://teampulse.telerik.com/view#item/291396
> Allow LivePatch plugin only in release configuration

- lib/services/plugins-service.ts
When marketplace plugin is renamed we have some issues with our implementation:
* when plugin had been installed, we check it by name. It has been chaned, so if you try adding it again, we add it once more to your configuration files.
* when you try to remove the plugin by name, we cannot find it and we do not remove it from the .abproject files.
All these operations should be based on plugin identifiers, not plugin name. Add code to check if the passed name is an old name of a plugin. As in our *.abproject files we keep the ids of the plugins, not their names, when user passes old name, we can get the old plugin id and see if it matches any of the installed plugin ids.
Add version printing when marketplace plugin is added (for example: "Plugin streethawk was successfully added for debug …
> Fix plugin commands for renamed marketplace plugins

- lib/commands/deploy.ts
http://teampulse.telerik.com/view#item/292890
> Release console after android deploy on device.

- lib/commands/web-view/list-web-views.ts
- lib/declarations.d.ts
- lib/services/web-view-service.ts
http://teampulse.telerik.com/view#item/293252
> Show currently active web view when listing web views

- lib/services/web-view-service.ts
http://teampulse.telerik.com/view#item/293371
> Respect correctly default version of corresponding webview's plugin

- README.md
To be merged when we're certain of the release date.
> Release frontmatter for 2.10

- README.md
- lib/commands/dev/prepackage.ts
- lib/declarations.d.ts
- lib/project/cordova-project.ts
- lib/project/nativescript-project.ts
- lib/project/project-constants.ts
- lib/project/project.d.ts
- lib/resource-loader.ts
- lib/services/nativescript-migration-service.ts
- lib/services/web-view-service.ts
- lib/templates-service.ts
Merge release in master (for 2.10.0)
> Merge release in master (for 2.10.0)

- docs/man_pages/general/autocomplete-disable.md
- docs/man_pages/general/autocomplete-enable.md
- docs/man_pages/general/autocomplete-status.md
- docs/man_pages/general/autocomplete.md
- docs/man_pages/general/doctor.md
- docs/man_pages/general/feature-usage-tracking-disable.md
- docs/man_pages/general/feature-usage-tracking-enable.md
- docs/man_pages/general/feature-usage-tracking-status.md
- docs/man_pages/general/feature-usage-tracking.md
- lib/bootstrap.ts
- lib/services/doctor-service.ts
See https://github.com/NativeScript/nativescript-cli/issues/480 and http://teampulse.telerik.com/view#item/294290
> Implement doctor command in AppBuilder CLI

- lib/login.ts
Add tracking of tenant edition and license. Use special names of the edition, similar to Mist.
Implements http://teampulse.telerik.com/view#item/293312
> Track user tenant information

- lib/commands/project/create.ts
- lib/declarations.d.ts
- lib/options.ts
- lib/services/screen-builder-service.ts
http://teampulse.telerik.com/view#item/294296
> Expose answers option in order to automate ScreenBuilder integration

- lib/services/screen-builder-service.ts
Fixes http://teampulse.telerik.com/view#item/296205
> Fix broken sb commands

- Gruntfile.js
- README.md
- lib/config.ts
- package.json
- test/stubs.ts
> Merge 2.10.1 in master

- lib/services/cordova-migration-service.ts
- test/cordova-migration-service.ts
fixes [Turn on Whitelist plugin when migrating to Cordova 4.0.0](http://teampulse.telerik.com/view#item/295506)
> Respect default enabled plugins

- docs/man_pages/project/creation/create-screenbuilder.md
- docs/man_pages/project/creation/create.md
- docs/man_pages/screenbuilder/add-about.md
- docs/man_pages/screenbuilder/add-authentication.md
- docs/man_pages/screenbuilder/add-dataprovider.md
- docs/man_pages/screenbuilder/add-field.md
- docs/man_pages/screenbuilder/add-form.md
- docs/man_pages/screenbuilder/add-list.md
- docs/man_pages/screenbuilder/add-view.md
IMPORTANT: To check the contents at the links replace docs with testdocs. Here's the address of the article: http://testdocs.telerik.com/platform/appbuilder/creating-your-project/screen-builder-automation
> --answers option for SB commands

- Gruntfile.js
Delete coverage dir from build package - this time really. Our package is buid with grunt pack command - add new async grunt task in order to delete the coverage directory.
http://teampulse.telerik.com/view#item/296352
> Delete coverage dir from build package - really

- docs/man_pages/project/configuration/prop-add.md
- docs/man_pages/project/configuration/prop-print.md
- docs/man_pages/project/configuration/prop-set.md
- docs/man_pages/project/testing/emulate-android.md
- docs/man_pages/project/testing/emulate-ios.md
- docs/man_pages/project/testing/remote.md
http://teampulse.telerik.com/view#item/295423
> Switching to kebab-case for two-worded options (where working)

- lib/declarations.d.ts
- lib/progress-indicator.ts
- lib/project.ts
- lib/services/appmanager-service.ts
- lib/services/build.ts
- lib/services/dependency-extensions-service-base.ts
- lib/services/publish-service.ts
Append new line after project execution regardless of whether it succeeded or failed.
> Refactor progress-indicator to append new line

- docs/man_pages/project/testing/build-wp8.md
- docs/man_pages/project/testing/emulate-wp8.md
- docs/man_pages/publishing/appmanager-upload-wp8.md
http://teampulse.telerik.com/view#item/286878
> Documenting http://teampulse.telerik.com/view#item/286878

- config/dependency-config.json
Latest changes include
* JSDO data source support
* Unique default values
Implements [#294209](http://teampulse.telerik.com/view#item/294209)
> Integrate ScreenBuilder v0.0.8

- .gitignore
- docs/man_pages/index.md
- docs/man_pages/project/configuration/edit-configuration.md
- docs/man_pages/project/configuration/mobileframework-set.md
- docs/man_pages/project/configuration/prop-add.md
- docs/man_pages/project/configuration/prop-print.md
- docs/man_pages/project/configuration/prop-remove.md
- docs/man_pages/project/configuration/prop-set.md
- docs/man_pages/project/configuration/prop.md
- docs/man_pages/project/configuration/resource-create.md
- docs/man_pages/project/configuration/resource.md
- docs/man_pages/project/configuration/webview-set.md
- docs/man_pages/project/configuration/webview.md
- lib/bootstrap.ts
- lib/commands/dev/prepackage.ts
- lib/commands/resource.ts
- lib/declarations.d.ts
- lib/options.ts
- lib/project.ts
- lib/project/cordova-project.ts
- lib/project/nativescript-project.ts
- lib/project/project-constants.ts
- lib/project/project.d.ts
- lib/project/web-site-project.ts
- lib/resource-loader.ts
- lib/services/image-service.ts
- lib/services/nativescript-migration-service.ts
- test/project-properties-service.ts
- test/stubs.ts
Automatically generate images based on one hi-res image.
Implements [#294236](http://teampulse.telerik.com/view#item/294236)
Merge after https://github.com/telerik/mobile-cli-lib/pull/377
> Implement automatic image generation

- test/resources/blank-NativeScript.abproject
Change the FrameworkVersion property so that it matches that on the server tempalate
> Update NativeScript FrameworkVersion in tests

- lib/services/nativescript-migration-service.ts
Add support fore {N} 1.1.2. During migration from older version to 1.1.2, we have to create package.json file (take it from nativescript resources directory). Make sure to keep this file when downgrading from 1.1.2 to older version.
http://teampulse.telerik.com/view#item/294271
> NOTE: This PR will fail until BpcTooling and Ice are not merged
> Support {N} 1.1.2

- package.json
> Set version to 2.11.0

- lib/services/doctor-service.ts
Implements http://teampulse.telerik.com/view#item/296931
> Enhance doctor command to report about missing Git

- docs/man_pages/screenbuilder/add-about.md
- docs/man_pages/screenbuilder/add-authentication.md
- docs/man_pages/screenbuilder/add-dataprovider.md
- docs/man_pages/screenbuilder/add-field.md
- docs/man_pages/screenbuilder/add-form.md
- docs/man_pages/screenbuilder/add-list.md
- docs/man_pages/screenbuilder/add-view.md
- docs/man_pages/screenbuilder/screenbuilder.md
Ping @ikoevska
This is a retarget from https://github.com/Icenium/icenium-cli/pull/1154
> Fix screenbuilder help `Related Commands`

- lib/commands/emulate.ts
Release the terminal when starting android emulator. Fixes: http://teampulse.telerik.com/view#item/297523
> Release the terminal when starting android emulator

- lib/commands/project/create.ts
- lib/commands/simulate.ts
- lib/declarations.d.ts
- lib/services/platform-services-run-validator.ts
- lib/services/simulatorPlatformServices.ts
This causes weird behavior on Linux as well as under other OS in which the simulator cannot be run (for example Windows without .NET Framework)
Fixes [#297486](http://teampulse.telerik.com/view#item/297486)
> Fix screenbuilder attempt to launch simulator regardless of OS

- config/dependency-config.json
Implements [297315](http://teampulse.telerik.com/view#item/297315)
> Integrate ScreenBuilder v0.0.9

- lib/bootstrap.ts
- lib/commands/live-sync.ts
- lib/config.ts
- lib/declarations.d.ts
- lib/providers/device-app-data-provider.ts
- lib/services/build.ts
- lib/services/livesync-service.ts
- test/stubs.ts
Fixes http://teampulse.telerik.com/view#item/297546
Should be fixed after this PR https://github.com/telerik/mobile-cli-lib/pull/397
> Apply livesync changes

- lib/commands/appmanager-livesync.ts
- lib/commands/appmanager.ts
- lib/commands/build.ts
- lib/commands/deploy.ts
- lib/commands/emulate.ts
- lib/commands/live-sync.ts
- lib/project/cordova-project.ts
- lib/service-util.ts
- lib/services/app-scaffolding-extensions-service.ts
- lib/services/dependency-extensions-service-base.ts
- lib/services/generator-extensions-service.ts
> Merge onpremise in master

- lib/services/screen-builder-service.ts
Instead of only collecting nested messages, collect all error messages
Fixes [#297901](http://teampulse.telerik.com/view#item/297901)
Ping @rosen-vladimirov @teobugslayer for a quick and painless review
> Fix screenbuilder error reporting

- package.json
> Set version to 2.11.1

- lib/bootstrap.ts
- lib/commands/remote.ts
- lib/declarations.d.ts
- lib/options.ts
- lib/services/remote-service.ts
- package.json
Fix bad command line - "--timeout null"
Fix bad command line - lunching from Graphite
Use ES6 imports
Added missing dependency in package.json - shelljs
Fixes http://teampulse.telerik.com/view#item/298968
> Refactor remote command

- lib/services/livesync-service.ts
Fixes http://teampulse.telerik.com/view#item/299038
> Fix android device-related commands

- test/resources/blank-NativeScript.abproject
Ping @rosen-vladimirov @Fatme @teobugslayer @Icenium/qa
> Fix testing {N} Framework version

- resources/command-help.json
- test/cloud-projects.ts
- test/commands-service.ts
- test/stubs.ts
As suggested by @ikoevska 
Merge after https://github.com/telerik/mobile-cli-lib/pull/451
> Fix command suggestions

- lib/services/multipart-upload.ts
- test/multipart-upload.ts
Fix the multipart upload where in some cases we produce last chunk with size larger than 20MB. The server returns error for such chunks.
> Fix multipart upload

- lib/bootstrap.ts
- lib/commands/deploy.ts
- lib/commands/emulate.ts
- lib/commands/itunes-connect.ts
- lib/declarations.d.ts
- lib/services/appmanager-service.ts
- lib/services/appstore-service.ts
- lib/services/build.ts
- lib/services/extensions-service-base.ts
After @mbektchiev's change the build returns more than one package def. Use the correct IPackageDef to get the built binary package
Fixes http://teampulse.telerik.com/view#item/300909
> Parse correctly build results

- docs/man_pages/publishing/appmanager-livesync.md
- lib/declarations.d.ts
- lib/options.ts
- lib/server-api.d.ts
- lib/services/appmanager-service.ts
http://teampulse.telerik.com/view#item/301163
> Add support for AppManager LiveSync mandatory app updates to CLI

- package.json
> Set version to 2.12.0

- ABIGNORE.md
Retargeting https://github.com/Icenium/icenium-cli/pull/1223
> Updated the template .abignore

- README.md
Retargeting the old https://github.com/Icenium/icenium-cli/pull/1222
> We have moved to .NET 4.5 on Windows

- docs/man_pages/index.md
- docs/man_pages/lib-management/kendoui-install.md
- docs/man_pages/lib-management/kendoui-notes.md
- docs/man_pages/lib-management/kendoui.md
- docs/man_pages/lib-management/plugin-add.md
- docs/man_pages/lib-management/plugin-configure.md
- docs/man_pages/lib-management/plugin-fetch.md
- docs/man_pages/lib-management/plugin-find.md
- docs/man_pages/lib-management/plugin-remove.md
- docs/man_pages/lib-management/plugin.md
Fix help of all plugins-related commands, so users will understand that
they can use them with {N} projects.
> Add help for NS plugins commands

- lib/server-api.d.ts
- lib/server-api.ts
[Related Sever PR](https://github.com/Icenium/Ice/pull/4354)
> Update server APIs

- lib/services/nativescript-project-plugins-service.ts
When plugin in referenced via local path or github url, `appbuilder plugin` command
does not show information about it.
Read the package.json of the local plugin in order to get data for it.
Install the plugin referenced with github url to temp dir and read its package.json.
Fixes http://teampulse.telerik.com/view#item/303583
> Print information about local plugins

- lib/declarations.d.ts
- lib/services/nativescript-migration-service.ts
Handles all migrations from and to versions below, above and mixed 1.4.3
Merge after https://github.com/telerik/mobile-cli-lib/pull/487
Refs
+ ["Deprecated" to {N} version - 0.10.0, 1.0.1](http://teampulse.telerik.com/view#item/302911)
+ [Warning confirmation when migrating from {N} <v1.4.3 to >=v1.4.3](http://teampulse.telerik.com/view#item/303459)
+ [Implement migration to and from {N} v1.4.3](http://teampulse.telerik.com/view#item/302904)
Ping @Fatme @teobugslayer @rosen-vladimirov
> Migrations from and to NS 1.4.3

- test/resources/blank-NativeScript.abproject
Fix unit tests that create {N} project to expect 1.4.3 version.
> Fix NativeScript project unit tests

- lib/commands/emulate.ts
Fix starting of iOS Simulator
Fixes http://teampulse.telerik.com/view#item/300209
> Fix starting of iOS Simulator

- lib/livesync-constants.ts
- lib/providers/device-app-data-provider.ts
- lib/services/livesync-service.ts
Fixes http://teampulse.telerik.com/view#item/299070
> Fix livesync --companion for ns projects

- package.json
> Set version to 2.14.0

- README.md
> Merge 2.12.1

- lib/commands/user-status.ts
- lib/login.ts
- lib/server-api.d.ts
Track user's edition type by using new property - editionType.
Implements http://teampulse.telerik.com/view#item/303569
> Track user's edition type by using tenant.editionType

- package.json
Fixes http://teampulse.telerik.com/view#item/281297
> Update ios-sim version

- lib/services/nativescript-project-plugins-service.ts
In nativescript project, when a plugin is added, CLI's trying to install it in local dir
in case you add it via github url or local dir.
The code is trying to detect the installation directory based on the output.
But with `npm 3+` the output is changed a lot, so we have to check the installation dir and see if there is node_modules dir there.
If we have such dir with only one package, this must be our package, so let's use it.
> Support npm 3+ when adding nativescript plugins

- README.md
To be merged when the release date is set in stone
> Updated sys reqs and fixed release info

- test/cloud-projects.ts
- test/commands-service.ts
- test/stubs.ts
Merge after https://github.com/telerik/mobile-cli-lib/pull/519
Ping @rosen-vladimirov @Fatme @teobugslayer
> Introduce warnWithLabel method in logger

- docs/man_pages/project/testing/emulate-ios.md
Fixes http://teampulse.telerik.com/view#item/300209
> Document --justlaunch

- README.md
- package.json
Set ios-sim-portable to working version and set version of appbuilder-cli to 2.14.1
Update README for 2.14.1
> Prepare 2.14.1 release

- lib/services/doctor-service.ts
- lib/services/livesync-service.ts
- lib/sys-info.ts
Update sys-info in order to use CLI's package.json.
> Update sys-info according to latest common changes

- lib/commands/deploy.ts
Fixes http://teampulse.telerik.com/view#item/306407
Update common lib, where the following change is applied:
Add canStartApplication to applicationManager
We have different cases when we can start the application, based on current platform and device platform.
Add `canStartApplication` in applicationManager's which evaluates all circumstances and can be used to check if we are able to start the application on device.
> Start android applications after deploy

- lib/service-util.ts
See http://teampulse.telerik.com/view#item/306963
> Fix update instructions

- docs/man_pages/project/testing/emulate-android.md
Fix Genymotion emulator starting by updating common lib, where a fix is applied for checking if running device is Genymotion emulator.
> Fix Genymotion emulator

- lib/commands/dev/config-apply.ts
It can cause problems in case-sensitive OS.
Ping @mbektchiev
> LowerCase the parameter passed to $ dev-config-apply

- docs/man_pages/project/configuration/mobileframework-set.md
- docs/man_pages/project/configuration/mobileframework.md
- docs/man_pages/project/configuration/prop-add.md
- docs/man_pages/project/configuration/prop-print-androidversioncode.md
- docs/man_pages/project/configuration/prop-print.md
- docs/man_pages/project/configuration/prop-remove.md
- docs/man_pages/project/configuration/prop-set-androidversioncode.md
- docs/man_pages/project/configuration/prop-set.md
- docs/man_pages/project/configuration/prop.md
- docs/man_pages/project/configuration/resource-create.md
- docs/man_pages/project/configuration/resource.md
- docs/man_pages/project/configuration/webview-set.md
- docs/man_pages/project/configuration/webview.md
- lib/bootstrap.ts
- lib/commands/prop/prop-print-android-version-code.ts
- lib/commands/prop/prop-print.ts
- lib/commands/prop/prop-set-android-version-code.ts
TP reference: [Inform the user about number appending upon android version code change](http://teampulse.telerik.com/view#item/306369)
Ping @rosen-vladimirov for code and @ikoevska for messaging
> Print info message upon android version code change

- lib/hooks/typescript-compilation.ts
- lib/project.ts
- lib/services/cordova-project-plugins-service.ts
- package.json
> Merge release in master

- lib/declarations.d.ts
- lib/services/cordova-migration-service.ts
- lib/services/cordova-project-plugins-service.ts
- lib/services/nativescript-project-plugins-service.ts
- lib/services/plugins-service.ts
- test/cordova-migration-service.ts
- test/project.ts
Write plugin identifier instead of name in package.json
In addition
* change/add messages upon plugin add/remove/fetch.
* allow installing plugins from `.tgz`
> Fix ns plugin add

- lib/services/nativescript-project-plugins-service.ts
Install the plugin in the temp directory, copy the plugin to project if needed and set dependency.
Ping @rosen-vladimirov @teobugslayer for review
> Enable adding plugins from .tgz or .tar.gz

- lib/commands/project/init.ts
See http://teampulse.telerik.com/view#item/309474
> Appbuilder init discovers Ionic projects as hybrid ones

- test/project.ts
- test/resources/blank-Cordova.abproject
> Update testing cordova .abproject FrameworkVersion

- lib/services/samples-service.ts
Set display name to the actual name of the sample only.
TP Reference: [[CLI] Unify {N} samples' display names](http://teampulse.telerik.com/view#item/310120)
Ping @rosen-vladimirov @teobugslayer
> Unify {N} samples' display names

- Gruntfile.js
Cleans and builds
Ping @teobugslayer
> Introduce `grunt rebuild`

- config/config-cacuat.json
ping @Mitko-Kerezov @rosen-vladimirov
> Add configuration file for CAC UAT environment

- tsconfig.json
Add tsconfig.json so when CLI is opened with VS Code, the autocompletion will work!
> Add tsconfig.json

- lib/config.ts
- test/stubs.ts
Update to latest common lib and add the new property of static config.
> Fix static config

- .idea/modules.xml
- lib/commands/project/init.ts
- lib/project.ts
- lib/project/project.d.ts
- test/stubs.ts
Only a spike
See http://teampulse.telerik.com/view#item/309474
> Import Ionic CLI projects

- lib/project.ts
- Improved message
- Fixed: if the user disapprove the update message,a ctually stop the process
- Fixed: correctly generate paths to existing ionic project files to delete
> Ionic enhancements

- test/resources/blank-NativeScript.abproject
Ping @rosen-vladimirov @teobugslayer
> Fix NS default version unit test

- lib/services/build.ts
When building the project with --download the configuration files for all platforms should be downloaded in .ab folder
Fixes http://teampulse.telerik.com/view#item/302390
> Move additional files in .ab folder

- config/config-caclive.json
ping @rosen-vladimirov @Mitko-Kerezov
> Update CAC UAT and add CAC LIVE config.jsons

- lib/services/remote-service.ts
Due to change in the names that AppBuilder CLI passes to ios-sim-portable, the remote command is not working when user's XCode version is 7.x
The current names work for XCode 6.x only.
Check the version of the XCode on the machine and pass correct names.
> Fix remote command

- lib/declarations.d.ts
- lib/services/doctor-service.ts
- lib/services/user-settings-service.ts
Includes minor refactoring:
* return future in doctor-service
* extend base user settings service
> Get latest common lib

- config/dependency-config.json
Implements [Integrate with Screen Builder's latest release - 0.0.17](http://teampulse.telerik.com/view#item/315524)
> Update Screen Builder to 0.0.17

- test/deploy.ts
Update to latest common lib and fix unit tests
> Update to latest common lib

- test/resources/blank-NativeScript.abproject
Set expected NS version to 2.0.0 in unit tests.
> Set expected NS version to 2.0.0

- docs/man_pages/project/testing/debug-android.md
- docs/man_pages/project/testing/debug-ios.md
- lib/bootstrap.ts
- lib/commands/debug.ts
- lib/declarations.d.ts
- lib/services/clipboard-service.ts
- lib/services/debug/darwin-debugger-service.ts
- lib/services/debug/win-debugger-service.ts
- package.json
Remove Xillium and use Safari's webinspector for iOS and Chrome's inspector for Android.
> Remove the old Mac debugger

- package.json
> Set version to 3.3.0

- lib/ionic-project-transformator.ts
When creating the backup of the project the AppBuilder project files are already added to the original project directory and they need to be excluded from the backup.
> Fix Ionic project backup

- lib/ionic-project-transformator.ts
- test/ionic-project-transformator.ts
The resources folder if the Ionic project is not needed in the AppBuilder project.
> Remove ionic resources folder

- test/ionic-project-transformator.ts
Need to add the resources folder in the test which is virifying that all assorted files and folders are deleted.
> Fix the tests for the ionic project transformation

- package.json
Need to increase the tests timeout because in some cases the tests for the Ionic project transformation are really slow.
> Increase tests timeout

- README.md
> Release date and system requirements

- lib/commands/dev/prepackage.ts
- prepublish.js
When executing the prepackage command we check if there are environment variables set by Jenkins for the sha of the commit (sha1) or for the branch name (BranchToBuild).
> Add cli branch to config.json

- package.json
> Set version to 3.3.1

- lib/commands/emulate.ts
- lib/commands/framework-versions/print-versions.ts
- lib/commands/framework-versions/set-version.ts
- lib/commands/itunes-connect.ts
- lib/commands/project/create.ts
- lib/commands/project/init.ts
- lib/commands/prop/prop-print-android-version-code.ts
- lib/commands/prop/prop-set-android-version-code.ts
- lib/declarations.d.ts
- lib/dynamic-help-provider.ts
- lib/options.ts
- lib/project.ts
- lib/project/cordova-project.ts
- lib/project/nativescript-project.ts
- lib/project/project.d.ts
- lib/project/resolvers/framework-project-resolver-base.ts
- lib/providers/commands-service-provider.ts
- lib/services/appmanager-service.ts
- lib/services/appstore-service.ts
- lib/services/build.ts
- lib/services/cordova-project-plugins-service.ts
- lib/services/livesync/livesync-service.ts
- lib/services/project-properties-service.ts
- lib/services/samples-service.ts
- test/build-configurations.ts
- test/deploy.ts
- test/ionic-project-transformator.ts
- test/project.ts
Includes changes for
* Prop set/print commands
* Build
* LiveSync (both regular and companion)
TP Reference: [Support environment configurations](http://teampulse.telerik.com/view#item/308175)
Ping @rosen-vladimirov @TsvetanMilanov for a **thorough** review
Tests are on the way!
> Implement configuration logic

- README.md
- package.json
> release >>> master

- README.md
> Update release date for 3.3.2

- config/dependency-config.json
- docs/man_pages/project/creation/create.md
- docs/man_pages/screenbuilder/add-authentication.md
- docs/man_pages/screenbuilder/add-dataprovider.md
- docs/man_pages/screenbuilder/add-editablelist.md
- docs/man_pages/screenbuilder/add-editablelistform.md
- docs/man_pages/screenbuilder/add-editablelistformfield.md
- docs/man_pages/screenbuilder/add-field.md
- docs/man_pages/screenbuilder/add-form.md
- docs/man_pages/screenbuilder/add-list.md
- docs/man_pages/screenbuilder/add-view.md
- docs/man_pages/screenbuilder/screenbuilder.md
- docs/man_pages/screenbuilder/upgrade-screenbuilder.md
- lib/services/app-scaffolding-extensions-service.ts
- lib/services/screen-builder-service.ts
Implements Integrate with Screen Builder's latest release - 0.0.17 [feature](http://teampulse.telerik.com/view#item/315524) and [story](http://teampulse.telerik.com/view#item/315789)
Ping @rosen-vladimirov @TsvetanMilanov and @ikoevska
> Screen Builder 0.0.17 integration

- lib/project.ts
- lib/project/project.d.ts
- lib/services/build.ts
Both when building for app and for companion. If no configurations present default to debug.
> Default to lexicographically first configuration

- lib/services/plugins/npm-plugins-service-base.ts
When we try to fetch plugin with dependencies npm 2 returns all installed dependencies on separate rows and the last row contains the plugin we want to fetch.
> Fix plugin fetch for plugins with dependencies

- lib/services/plugins/cordova-project-plugins-service.ts
- lib/services/plugins/nativescript-project-plugins-service.ts
- lib/services/plugins/npm-plugins-service-base.ts
We need to respect the --default option when adding NS plugin and also we need to change the sorting of the plugin versions when we get the latest plugin verison.
> Respect default option when adding NS plugin

- lib/services/app-scaffolding-extensions-service.ts
If the user machine has npm 3 we don't need to run `$ npm dedupe` because npm itself dedupes dependencies while installing them.
This fixes [[CLI] Cannot install ScreenBuilder with node 6.x](http://teampulse.telerik.com/view#item/318297)
Merge after https://github.com/telerik/mobile-cli-lib/pull/763
> Only execute npm dedupe if npm major version is not 3

- lib/commands/appmanager-livesync.ts
- lib/services/appmanager-service.ts
- lib/services/plugins/nativescript-project-plugins-service.ts
General changes:
- Extending `appmanager-service` to support {N} apps.
- __appmanager livesync__ command should support only iOS and Android {N} apps.
Nativescript plugins service changes (`nativescript-project-plugins-service`):
-  Introduced "Advanced Plugins" section when showing available plugins to the user. _I found the name "Featured Plugins" a lot more appropriate but i guess it should be consistent with Cordova?_
I've decided to introduce `getFeaturedNpmPackages` that can handle more than one plugin that needs to show up under "Advanced Plugins". But I could remove it and `concat` manually the AM LiveSync plugin as an 'Advanced Plugin' since for now we only have one plugin to display there. 
- Skipping variables configuration when adding AM LiveSync plugin since they are not …
> Enable AM LiveSync feature for {N} apps.

- lib/bootstrap.ts
- lib/declarations.d.ts
- lib/project/nativescript-project.ts
- lib/providers/date-provider.ts
- test/nativescript-project.ts
- test/project.ts
Add unit tests to test the functionality of nativescript-project.
> Add tests for nativescript project

- lib/services/plugins/nativescript-project-plugins-service.ts
The package.json information returned from the npm service is an object and when we construct the NS plugin data we expect it to be a string and JSON.parse() fails.
> Fix unexpected token o

- lib/services/project-migration-service.ts
- test/stubs.ts
After we migrate TS projects we should delete the typings directory if it is empty after we remove the tns-core-modules directory.
> Delete typings dir if it is empty

- lib/project/cordova-project.ts
Update projects that are using Cordova 4.0.0 (Android 4.0.2) to use the Cordova 4.1.1 and inform the user for this action.
TP reference [Update project's that are using Cordova 4.0.0 (Android 4.0.2) to use the Cordova 4.1.1](http://teampulse.telerik.com/view#item/310575)
> Implement force upgrade logic for projects using cordova android 4.0.2

- config/config-base.json
- lib/declarations.d.ts
- lib/hooks/typescript-compilation.ts
- lib/project.ts
- lib/project/project.d.ts
- lib/services/nativescript-migration-service.ts
- lib/services/plugins/nativescript-project-plugins-service.ts
- lib/services/project-migration-service.ts
- test/plugins-service.ts
Update the TypeScrypt compilation hook to use the updated methods from the typescript-service.
> Update TypeScript compilation hook

- README.md
Update README.md for 3.4.3 release
> 3.4.3 README

- test/resources/blank-NativeScript.abproject
Fix expected NativeScript version in unit tests.
> Fix unit tests

- README.md
Set correct release date for 3.4.3
> Set correct release date for 3.4.3

- .vscode/launch.json
- lib/services/samples-service.ts
Track projects which are created from samples.
> Track project created from samples

- lib/commands/plugin/fetch-plugin.ts
- lib/plugins-data.ts
- lib/services/plugins/cordova-project-plugins-service.ts
- lib/services/plugins/nativescript-project-plugins-service.ts
- lib/services/plugins/plugins-service-base.ts
- test/plugins-service.ts
Display fetched plugins.
We should display the fetched plugins in Cordova projects when we list the installed plugins.
Move the prompter in the plugin source and add version parameter when fetching plugin.
> Improve fetched plugins operations

- docs/man_pages/project/creation/init.md
Update the description of the init command because we can create AppBuilder project from Ionic project.
> Update init command description

- lib/service-util.ts
Requests to registry.npmjs.org may often hang, which blocks CLI's execution. Wait for five seconds and in case there's no result, show warning to the user and consider the version as valid.
> Do not wait for hang request to registry.npmjs.org

- lib/services/appmanager-service.ts
http://teampulse.telerik.com/view#item/321452
> Sort the returned appmanager groups list.

- lib/ionic-project-transformator.ts
- lib/services/plugins/cordova-project-plugins-service.ts
In the Ionic project template in the plugins directory is added fetch.json file. Before we get the information of the local plugins we need to check if the entry in the plugins directory is file or directory.
Fixes: http://teampulse.telerik.com/view#item/322371
> Fix Ionic project transformation

- README.md
- package.json
Change the version to 3.5.2 in package.json file and update the README.md file.
> Change version to 3.5.2

- lib/appbuilder-cli.ts
- test/stubs.ts
> Deprecate Node 0.12

- README.md
- package.json
Change version to 3.6 and update readme.
> Change version to 3.6 and update readme

- README.md
- package.json
> Update version to 3.6.1

- README.md
- package.json
Change the version in package.jsonto 3.6.3 and update the README.md.
> Change version to 3.6.3

- README.md
- package.json
> Bump version to 3.6.7

- lib/services/cordova-migration-service.ts
- test/project.ts
- test/resources/blank-NativeScript.abproject
> Fix failing tests

- lib/project.ts
- lib/services/appstore-service.ts
We need to wait the method instead of the apple id.
> Fix await in the appstore upload command

- lib/services/app-scaffolding-extensions-service.ts
- lib/services/doctor-service.ts
- lib/sys-info.ts
We have added one parameter in the filter method which we do not need and we do not respect it when we call the method. The solution is to remove it.
Common lib reference: https://github.com/telerik/mobile-cli-lib/pull/905
> Fix device log filter

- docs/man_pages/general/autocomplete-enable.md
- docs/man_pages/general/autocomplete-status.md
- docs/man_pages/general/autocomplete.md
- docs/man_pages/general/doctor.md
- docs/man_pages/general/error-reporting.md
- docs/man_pages/general/proxy-clear.md
- docs/man_pages/general/proxy-set.md
- docs/man_pages/general/proxy.md
- docs/man_pages/general/usage-reporting.md
- docs/man_pages/index.md
- lib/config.ts
Cherry-pick https://github.com/Icenium/icenium-cli/pull/1650 in release
> Add docs for proxy commands

- README.md
- package.json
Set the version in package.json to 3.7.1 and update the README.md.
> Set the version to 3.7.1

- README.md
- docs/man_pages/general/proxy-set.md
- lib/commands/deploy.ts
- package.json
- test/deploy.ts
Conflicts:
* docs/man_pages/general/proxy-set.md
* lib/common
* package.json
> Merge release into master

- package.json
The new version contains some fixes regarding file upload on iOS devices
> Update ios-device-lib version

- README.md
- package.json
> Bump version to 3.7.2

- docs/man_pages/index.md
> Fix wrong link for proxy help

- README.md
- package.json
Bump the version to 3.7.5 and update the README.md file.
> Bump version to 3.7.5

- docs/man_pages/index.md
- docs/man_pages/screenbuilder/add-about.md
- docs/man_pages/screenbuilder/add-authentication.md
- docs/man_pages/screenbuilder/add-dataprovider.md
- docs/man_pages/screenbuilder/add-field.md
- docs/man_pages/screenbuilder/add-form.md
- docs/man_pages/screenbuilder/add-list.md
- docs/man_pages/screenbuilder/add-view.md
- docs/man_pages/screenbuilder/screenbuilder.md
- docs/man_pages/screenbuilder/upgrade-screenbuilder.md
- test/help.ts
Fix help for ScreenBuilder commands which were incorrectly shown in the terminal. Also add tests for changes in html-help-service.
> Fix help for ScreenBuilder commands

- README.md
Fix the release date in the README.md file.
> Fix README.md for 3.7.5 release

- package.json
Update `ios-device-lib` to latest version, where several bugfixes are included.
> Update ios-device-lib to latest version

- lib/bootstrap.ts
Register iOSNotificationService in injector, which will fix deployment on iOS devices.
> Register iOSNotificationService in injector

- README.md
Set correct date for 3.7.6 release
> Set correct date for 3.7.6 release

- lib/services/cloud-projects-service.ts
- test/cloud-projects.ts
Framework should be passed as `tns` instead of `NativeScript`
> Fix {N} export
