lib/bootstrap.ts, lib/commands/project.ts, lib/declarations.d.ts, lib/project.ts, resources/help.txt, test/project.ts
Add init|*unknown command which can be used to automatically determine project type.
Add logic to determine project type when executing appbuilder init based on the files in the directory:
- NativeScript project must contain tns_modules dir and app/bootstrap.js file.
- Hybrid project must contain cordova.ios.js, cordova.android.js and cordova.wp8.js
- Mobile Website project must contain index.html
Additional logic:
- NativeScript project cannot contain index.html or cordova.*.js files or index.html.
- Hybrid project and Mobile Website projects cannot contain tns_modules dir and app\bootstrap.js file.
If we are unable to determine project type, error message is shown and command's help is printed.
http://teampulse.telerik.com/view#item/269498
=> Init command to determine project type

package.json
Change package.json to use vladimirov/fibers_1_0_5_fixes branch where node-fibers are built with all latest fixes. This is a temporary change that has to be removed after merging vladimirov/fibers_1_0_5_fixes into master of node-fibers repo. The temp change is required for testing purposes.
=> Use vladimirov/fibers_1_0_5_fixes branch for node-fibers

lib/services/plugins-service.ts
getInstalledPlugins and getInstalledPluginsEnabledAtLeastInOneConfiguration methods were almost identical
=> Minor code refactor for the plugins-service

package.json
Update package.json to use ios-sim from its master branch. This is temporary in order to be able to test latest changes of node fibers (which are merged in ios-sim master). Related to http://teampulse.telerik.com/view#item/282879
=> Use ios-sim from master

lib/options.ts
Fix usage of shorthands, so when you specify -t for example to really use specified template. Update common lib where shorthands for help command had been added.
http://teampulse.telerik.com/view#item/284030
=> Fix usage of shorthand options

test/project.ts
Remove ")" from the end of some unit tests names. Update common lib where the following change is applied:
Add toString() call before calling toLowerCase() to make sure the value is a string. This prevents exception when passed value is a number.
Fixes http://teampulse.telerik.com/view#item/284099
=> Fix exception in getCommandName

config/config-release.json
Download times went from 03:26 min to 00:17 min.
=> Turn on downloading of debugging tools & simulator from the CDN.

lib/services/project-simulator-service.ts
Add correct set of --plugins when starting simulator, in cases when CorePlugins are not defined.
Fixes http://teampulse.telerik.com/view#item/284384
=> Improve error when unable to pass simulator params

lib/commands/prop/prop-add.ts, lib/commands/prop/prop-command-base.ts, lib/commands/prop/prop-print.ts, lib/commands/prop/prop-remove.ts, lib/commands/prop/prop-set.ts, lib/declarations.d.ts, lib/json-schema/json-schema-validator.ts, lib/options.ts, lib/project.ts, lib/project/project.d.ts, lib/services/project-properties-service.ts, resources/help.txt
Add validValue to options. When it is specified, all valid values of the requested property will be printed. Improve prop print command to work in the following way:
I. inside project dir:
1. $ appbuilder prop print -> prints all properties of current project and their current values
2. $ appbuilder prop print --validValue -> prints all properties valid for the current project and all valid values for each of them.
3. $ appbuilder prop print <PropName> -> prints the value of the property for the current project
4. $ appbuilder prop print <PropName> --validValue -> prints all valid values for the selected property, applicable to the current project type.
II. Outside of project dir:
1. $ appbuilder prop print -> leads to error, that no project is found
2. $ appbuilder prop print …
=> Add --validValue option to prop print command

lib/commands/itunes-connect.ts, lib/project.ts
Improve the error message when non-Corodova project is used.
Fixes http://teampulse.telerik.com/view#item/283182
=> Allow only Cordova projects to be published in the appstore

test/project.ts
As Friends template is no longer downloaded, we must remove the test that's checking its files in order to fix the build.
http://teampulse.telerik.com/view#item/284783
=> Remove Friends template test

resources/help.txt
The bug is the wrong case of a single symbol, which prevents dynamic calls from working
=> Fix error when trying to show the help for the create website command

lib/project.ts, lib/services/project-properties-service.ts, resources/json-schemas/WP.json, resources/project-properties-cordova.json, test/commands-service.ts, test/hash-service.ts, test/project.ts, test/resources/blank-cordova.abproject, test/stubs.ts
Add check for current Windows Phone SDK in .abproject (WPSdk) and when migrating it (using prop set) check if the new value is supported in the current Cordova version. As WP 8.1 SDK is supported in Cordova 3.7.0 and above, if the project is trying to use WP 8.1 SDK and its version is 3.5.0 or below, a prompt message suggests to use newer Cordova version. In case user is migrating his Framework version to a lower than 3.7.0 we check WPSdk value and if it is 8.1, we prompt the user to use 8.0.
http://teampulse.telerik.com/view#item/284537
=> Windows Phone SDK updates

lib/declarations.d.ts, lib/project.ts, lib/services/build.ts
Fix issue that migrated framework value is not saved in .abproject (when using $appbuilder prop set WPSdk 8.1). Fixed issue that migrated WPSdk version is not saved in .abproject(when using $appbuilder prop set FrameworkVersion 3.5.0). Fixed typo when checking for Experimental version.
=> Fix WPSdk setting

lib/commands/appmanager.ts, lib/declarations.d.ts, lib/services/build.ts, lib/validators/cryptographic-identity-validators.ts
Uploading application in AppManager now uses the following rules for certificates/provisions:
- android upload should work no matter of the certificate. If user had not specified certificate, we'll print warning and we'll use server's debug certificate
- ios upload cannot use AppStore provisioning (Development, AdHoc and Enterprise are allowed)
http://teampulse.telerik.com/view#item/284661
=> Update TAM Publishing

lib/project/framework-project-base.ts
In case you have CorePlugins defined in .abproject only (not in .debug.abproject and .release.abproject) you cannot build your project. Add check if the property is defined in the configuration specific files and if not - check for it in .abproject.
Fixes http://teampulse.telerik.com/view#item/284955
=> Fix using of properties from configuration specific .abproject

lib/commands/debug.ts, lib/commands/edit-configuration.ts, lib/commands/simulate.ts, lib/host-info.ts, lib/options.ts
If user cannot use 7zip, he is unable to create projects, unable to build etc. So on post-install we check if we are able to execute the 7za file and if ENOENT is return we show the user where he can find system requirements.
Fix host-info paths in some files and remove host-info reference from some other files.
Remove duplicated methods from host-info files (they exist on two places - in common lib and here).
http://teampulse.telerik.com/view#item/285027
=> Add check if 7za can be executed

lib/services/build.ts, lib/services/multipart-upload.ts
We start all chunk uploads simultaneously as fibers are started on process.nextTick. Limit them to three simultaneously by waiting the batch of three before creating the next three chunks. Add message to indicate uploading project to server.
It is part of http://teampulse.telerik.com/view#item/283781
=> Fix error when uploading large projects

lib/services/build.ts
In case you specify --provision, an error is thrown. Replace incorrect Server.ProvisionType.AppStore with constants.ProvisionType.AppStore
http://teampulse.telerik.com/view#item/285210
=> Fix appmanager upload ios with specified provision

lib/project.ts, lib/services/project-properties-service.ts, test/project.ts, test/resources/blank-NativeScript.abproject
Move completion of properties before validation of the project in order to have correct WP8 props.
If .abproject is missing projectVersion we print warning and add it.
In old project instead of Framework, we had projectType - in case we find projectType in .abproject, replace it with Framework.
http://teampulse.telerik.com/view#item/285225
=> Improve .abproject prop completion

lib/services/marketplace-plugins-service.ts
Fixes http://teampulse.telerik.com/view#item/281518
Sometimes server returns empty url address but we actually have the url from the response from `telerik.plugins.com`. This is only temporaly fix. After integrating the feature for marketplace plugin versioning we should delete this code.
=> Show plugin url for marketplace plugins

lib/declarations.d.ts, lib/plugins-data.ts, lib/services/marketplace-plugins-service.ts
If plugin is verified its publisher is Telerik or Telerik Partner. When showing info for plugins, if it is verified we show Telerik, or Telerik Partner.  Add IPublisher interface and modify MarketplacePluginData to handle verified plugins.
Fixes http://teampulse.telerik.com/view#item/280939
=> Add verified publisher for marketplace plugins

lib/commands/appmanager.ts, lib/services/build.ts, resources/help.txt
If you are using Development provision and you execute $appbuilder appmanager upload ios, the .ipa is downloaded. But if your provision is any other type or you upload for any other platform, the project is not downloaded. Change build code to download project with development certificate only if it is not build for appmanager. Use --download option with appmanger upload command in order to download the file.
http://teampulse.telerik.com/view#item/285204
=> Add --download option to appmanager upload

lib/commands/emulate.ts, lib/declarations.d.ts, lib/project.ts, lib/project/cordova-project.ts, lib/project/nativescript-project.ts, lib/project/project.d.ts, lib/project/web-site-project.ts, lib/services/emulator-settings-service.ts
Fix getProjectTargets of nativescript-project to be "android" and "ios" (remove code which was checking for bootstrap.android.js and bootstrap.ios.js). Fix emulate command to use appIdentifier directly (without using AppIdentifier class and passing incorrect options.companion option to it). Remove projectTargets property of project, as there is getProjectTargets method, which is used almost everywhere when we need project targets (fixed the only place where the projectTargets property was used).  Add emulate option to project capabilities in order to forbid emulate of mobile-website projects. EmulatorSettingsService checks for emulate capability and fails in case the project cannot be emulated.
NOTE: This PR allows to deploy nativescript projects to native emulator. For Android, the …
=> Fix emulate of NativeScript projects

lib/services/project-properties-service.ts
If projectVersion is missing from .abproject, we should set it to 1. Fix the code to set it to number 1, not string 1.
http://teampulse.telerik.com/view#item/285484
=> Fix projectVersion completion

lib/helpers.ts, lib/project.ts
"$ appbuilder prop print" and "$ appbuilder prop print CorePlugins" do not print the values of the configuration specific properties. Use cli-table to print the values of all configuration specific properties for all configurations (it will work no matter how much configurations we add in the future).
Fixes http://teampulse.telerik.com/view#item/285533
=> Print configuration specific properties

package.json
Update package.json to use fibers version 1.0.5.0 (it is the same as the currently used from branch vladimirov/fibers_1_0_5_fixes.
Use ios-sim-portable version 1.0.1 - it is the same as the master branch.
IMPORTANT: This pull request can be merged ONLY AFTER we publish version 1.0.1 of ios-sim-portable.
=> Update fibers and ios-sim usage

lib/config.ts, lib/project.ts, lib/project/cordova-project.ts, lib/project/nativescript-project.ts, lib/project/project.d.ts, lib/project/web-site-project.ts, test/stubs.ts
NativeScript projects are successfully installed on emulators and devices, but they are not started. The reason is incorrect startPackageActivity - it is project dependant. Add startPackageActivity for each projectType and set staticConfig's START_PACKAGE_ACTIVITY to it when emulate or deploy command is executed.
Fixes http://teampulse.telerik.com/view#item/285489
=> Fix starting of nativescript projects on device

lib/services/plugins-service.ts
Fixes http://teampulse.telerik.com/view#item/283257
=> Don't add CordovaPluginsVariables property in configuration specific files  when the plugin doesn't have variables

lib/project.ts
If in the configuration specific files (.debug.abproject or .release.abproject) there is property with value object ("prop": { "key1": "value1", "key2": "value2" }), we print "Object object" with $ appbuilder prop print. Add method to read all key-value pairs from such objects and show them. If any of the value is another object, we'll print its key-value pairs as well, but they'll be indented, to show that they are part of the upper value.
Fixes http://teampulse.telerik.com/view#item/285701
=> Print correctly objects from config files

lib/commands/remote.ts, resources/help.txt
With latest XCode, when you try starting simulator with sudo, the application is not started. Currently we are using sudo when user wants to use port below 1024. Even if they use $ sudo appbuilder remote 444, the application will not start because of the bug in XCode. So using ports below 1024 is useless. That's why we forbid using them.
Fixes http://teampulse.telerik.com/view#item/285912
=> Forbid ports below 1024

preuninstall.js
Preuninstall script tries to execute adb from resource/platform-tools... but we have moved the adb file in lib/common/platform-tools... so the script should check the path to adb.
=> Preuninstall script should use correct adb path

lib/commands/remote.ts
If you execute $ sudo appbuilder remote 444 we do not fail. Fix this.
Fixes: http://teampulse.telerik.com/view#item/285912
=> Forbid ports below 1024 with sudo

config/config-dev.json, config/config-dev1.json, config/config-dev2.json, config/config-local.json, config/config-sit.json, config/config-sttap.json, config/config-test.json
- Change local to point to sit-platform. That's why I've removed sit config.
- Remove dev1 and dev2 as they do not seem to work (also we've used them only once).
- Remove uat as it does not exist anymore.
- Change test to point to testtap.telerik.com (old address is redirected to this one).
- Change dev to point to mocktap.telerik.com NOTE: AppBuilder's deployment configuration on mocktap will be from release. This is local live environment.
- Add dev3 configuration - NOTE: AppBuilder's deployment configuration is Test.
=> Update configs according to latest changes

lib/services/build.ts
This code is not working with lodash 3.2. I added `.value()` call to trigger each callback execution.
=> Refactor code that shows qr codes to work with lodash 3.2

lib/project.ts
In some of our samples projectVersion is set to "1". Our code expects number, so the validation fails. Other clients (VSE, Graphite) allow using string for project version, so we use toString in order to allow "1". Json schemas allow both integer and string for projectVersion.
Fixes http://teampulse.telerik.com/view#item/286619
=> Allow projectVersion to be string

package.json
Change version to 2.8.2
Use ios-sim-portable 1.0.4 and ref-struct from telerik fork.
http://teampulse.telerik.com/view#item/285800
=> Support Nodejs 0.12

lib/project/cordova-project.ts, lib/project/nativescript-project.ts, lib/project/project-files-manager.ts, test/edit-configuration.ts
Mobile.Android.ManifestXml.zip on the server had been renamed to Mobile.Cordova.Android.ManifestXml.zip  Also there's additional file - Mobile.NativeScript.Android.ManifestXml.zip  which is used now. This breaks our unit tests and $ appbuilder edit-configuration android-manifest calls.
Add cordova-android-manifest and nativescript-android-manifest configs in order to fix the issue.
=> Fix edit-configuration command

lib/declarations.d.ts, lib/project/cordova-project.ts, lib/services/build.ts, lib/services/project-properties-service.ts, resources/json-schemas/WP.json, test/resources/blank-Cordova.abproject
Add required properties in order to be able to publish apps that target WPSdk 8.1. Add warning when calling $ appbuilder build wp8 --release --download (this is the common way to publish app to WP Store - build in release configuration and download the xap) and when calling $appbuilder appmanager upload wp8. Add code to complete these properties if they do not exist in current abproject.
http://teampulse.telerik.com/view#item/286652
=> Allow publishing with WPSdk 8.1

lib/project/cordova-project.ts, test/resources/blank-Cordova.abproject
Use the following format as default "1234Telerik." so you can use project names with the max length 30 symbols.
Fixes http://teampulse.telerik.com/view#item/286977
=> Fix WP8PackageIdentityName setting

lib/services/build.ts
Build method has BuildSettings passed as parameter. Respect the configuration passed in these settings (if it has such). This fixes the problem that calling $ appbuilder appstore upload <app_name> builds the app in Debug configuration and it is rejected by iTunes. The command correctly sets BuildSettings configuration to release, but build method does not respect it.
Fixes http://teampulse.telerik.com/view#item/287256
=> Respect configuration passed to build method

Gruntfile.js
Support scenario where ResourceDownloadEnvironment and DeploymentEnvironment are different. This is required when testing new release.
Fix default environment to be sit instead of local.
=> Fix gruntfile

lib/project/cordova-project.ts, test/project.ts, test/resources/blank-Cordova.abproject
As we've decided to use same default value for WP8PackageIdentityName, which is 1234Telerik.\<appid\>, I've changed the getCorrectWP8PackageIdentityName to use AppIdentifier property. In case the value is longer than 50 symbols, only the first 50 are taken.
Add unit tests.
http://teampulse.telerik.com/view#item/287429
=> Use AppIdentifier when setting WP8PackageIdentityName

lib/bootstrap.ts, lib/commands/appmanager.ts, lib/commands/build.ts, lib/commands/deploy.ts, lib/commands/live-sync.ts, lib/declarations.d.ts, lib/dynamic-help-provider.ts, lib/services/appmanager-service.ts, lib/services/livesync-service.ts, resources/help.txt, test/help.ts
Refactor several commands in order to be mobile platform specific - deploy, build, livesync, appmanager upload.
Update help.txt to support boolean conditions in order to understand if part of the help.txt should be included in the output.
Use lodash _.template in order to allow using of javascript code directly in help.txt file.
In case you want to call some method that returns string and you need the string in help.txt just write:
Some text... <%= this.$injector.resolve("project").myMethod() %> or even simpler:
Some text... <%= #{project.myMethod} %>
The code between <%= and %> will be executed (it's pure javascript, but you are able to use our $injector and $dynamicHelpService) and the returned string will be placed in the help file.
In case you want to limit some text only for specific …
=> Show context specific help

lib/project/nativescript-project.ts
Use new NativeScript templates. Replace TypeScript written by user with TS which is the actual name of the template. Replace TS. with TypeScript when showing available templates.
=> Use new NativeScript template names

resources/help.txt
Update common lib where a fix for hierarchical commands had been applied. Add help for new commands - '$ appbuilder device android' and '$ appbuilder device ios'
Fix is part of http://teampulse.telerik.com/view#item/283188
=> Fix hierarchical commands

lib/commands/simulate.ts
Simulator has two new parameters that have to be passed: New command line arguments added:
"isfeaturetrackingenabled" : boolean;
"analyticsaccountcode" : string.
Update common lib where a new method to get if analytics is enabled had been added.
http://teampulse.telerik.com/view#item/286925
=> Pass correct parameters to simulator to enable feature tracking

lib/bootstrap.ts, lib/commands/appmanager.ts, lib/commands/build.ts, lib/commands/debug.ts, lib/commands/deploy.ts, lib/commands/emulate.ts, lib/commands/live-sync.ts, lib/commands/project.ts, lib/config.ts, lib/mobile-platforms-capabilities.ts, lib/project.ts, lib/project/cordova-project.ts, lib/project/nativescript-project.ts, lib/resource-loader.ts, lib/services/analytics-settings-service.ts, lib/services/appmanager-service.ts, lib/services/build.ts, lib/services/livesync-service.ts, lib/services/project-properties-service.ts, lib/templates-service.ts, test/build-configurations.ts, test/project.ts, test/stubs.ts
Common lib is used by several CLIs - appbuilder-cli, nativescript-cli, etc. 
- There are several places where appbuilder is used, while it should be staticConfig.CLIENT_NAME. Fix all of these.
- Replace MobileHelper's exported functions in a new class - MobileHelper. This way we can resolve it from injector and it can easily use staticConfig's CLIENT_NAME. 
- Remove DevicePlatforms enum and add DevicePlatformsConstants class which can be used instead of the enum. 
- Add SYS_REQUIREMENTS_LINK to StaticConfig in order to have different links for each CLI. 
- Add getClientName and getPrivacyPolicyLink methods to IAnalyticsSettingsService.
http://teampulse.telerik.com/view#item/287728
=> Replace  appbuilder strings with CLIENT_NAME

lib/commands/remote.ts, lib/mobile-platforms-capabilities.ts
Remote command can work only on MacOS. Forbid using it on any other platform. Move some duplicate logic from execute method of RemoteCommand to validate method of PortCommandParameter.
Minor fix in mobile-platforms-capabilities where the property used to cache platforms, never received value, so the caching was not really working.
Fixes http://teampulse.telerik.com/view#item/287833
=> Forbid remote command on Windows and Linux

lib/bootstrap.ts, lib/services/livesync-service.ts
Fix bootstrap, where livesync <platform> commands had been required from incorrect file. Fix livesyncService where the platform variable had been reset, so the passed one was not used.
Fixes http://teampulse.telerik.com/view#item/287904
=> Fix livesync commands

lib/commands/emulate.ts
Fixes http://teampulse.telerik.com/view#item/287958
=> Remove hardcoded "Debug" configuration when starting ios emulator

.gitignore, .npmignore, AppBuilderCLI.njsproj, AppBuilderCLI.sln
Add Visual Studio project file. You must use Node Tools for Visual Studio in order to make it work. Right-click the project name in Visual Studio, select Properties and in script arguments you can add the command that you want to be executed.
NOTE: In order to compile the project correctly, this PR should be merged.
https://github.com/Icenium/icenium-cli/pull/895
=> Add Visual Studio project file

.npmignore, AppBuilderCLI.njsproj, preuninstall.js
Fix installation of appbuilder-cli by removing ProjectTemplates, ItemTemplates, etc. directories from .npmignore file. This way our resources are uploaded to npm and we are working fine.
Fix preuninstall script which was failing on several places (missing lodash as it was not required, unable to resolve injector, etc.) In order to fix the issues, new command  "dev-preuninstall" is introduced. This way injector can be resolved.
=> Fix installation and uninstall of CLI

AppBuilderCLI.njsproj
When you write `$ appbuilder`  we automatically open index.html in your default html editor. Change this behavior to show index.md in the console (full list of commands). The behavior now is:
`$ appbuilder` - shows full list of commands in the console
`$ appbuilder help` - shows full list of commands in the browser
`$ appbuilder -h` - same as `$ appbuilder` - shows full list of commands in the console
`$ appbuilder help -h` - shows help for "help" command in the console
`$ appbuilder help help` - shows help for "help" command in the browser
=> Fix console help when arguments are not passed

AppBuilderCLI.njsproj, docs/man_pages/general/autocomplete-disable.md, docs/man_pages/general/autocomplete-enable.md, docs/man_pages/general/autocomplete-status.md
Move autocompletion code to a new shell file. In .bash_profile, .bashrc and .zshrc add code that executes this code when we want to enable autocompletion.
Autocomplete is now hierarchical command. The subcommands and their behavior is:
* `autocomplete` - checks if autocompletion is enabled. In case it is not, ask the user for confirmation. In case autocompletion is enabled, but it is the old one (where we've written some data to .bash_profile, etc.), silently remove the old code and use the new approach. In case the user chooses to not use autocompletion, call disableAutocCompletion in order to remove all autocompletion code from all shell profiles.
* `autocomplete enable` - enables autocompletion in case it is not already enabled.
* `autocomplete disable` - disables autocompletion in …
=> Improve autocompletion

config/dependency-config.json, lib/commands/project/create.ts, lib/declarations.d.ts, lib/helpers.ts, lib/options.ts, lib/providers/commands-service-provider.ts, lib/services/app-scaffolding-extensions-service.ts, lib/services/dependency-extensions-service-base.ts, lib/services/extensions-service-base.ts, lib/services/generator-extensions-service.ts, lib/services/screen-builder-service.ts, lib/services/server-extensions.ts
This PR fixes 2 problems with ScreenBuilder integration:
1. Currently we are creating files in the current dir - I fixed this behavior and we create directory with appName.
2. Long paths on windows - I moved ScreenBuilder cache directory to <%localappdata%>/Telerik
Should be merged after this https://github.com/telerik/mobile-cli-lib/pull/257
=> Integrate new ScreenBuilder version

preuninstall.js
In some cases the preuninstall operations requires some more time and leads to errors if we do exit immediately. Add timeout of 3 seconds (it was removed with one of the previous commits by mistake).
Sync with latest common lib.
=> Add timeout on preuninstall

AppBuilderCLI.njsproj, docs/man_pages/index.md, docs/man_pages/publishing/appmanager-livesync.md, docs/man_pages/publishing/appmanager-upload-android.md, docs/man_pages/publishing/appmanager-upload-ios.md, docs/man_pages/publishing/appmanager-upload-wp8.md, docs/man_pages/publishing/appmanager.md, docs/man_pages/publishing/appstore-list.md, docs/man_pages/publishing/appstore-upload.md, docs/man_pages/publishing/appstore.md, docs/man_pages/publishing/certificate-create-self-signed.md, docs/man_pages/publishing/certificate-export.md, docs/man_pages/publishing/certificate-import.md, docs/man_pages/publishing/certificate-remove.md, docs/man_pages/publishing/certificate-request-create.md, docs/man_pages/publishing/certificate-request-download.md, docs/man_pages/publishing/certificate-request-remove.md, docs/man_pages/publishing/certificate-request.md, docs/man_pages/publishing/provision-import.md, docs/man_pages/publishing/provision-remove.md, docs/man_pages/publishing/provision.md, lib/bootstrap.ts, lib/commands/appmanager-livesync.ts, lib/declarations.d.ts, lib/server-api.d.ts, lib/server-api.ts, lib/services/appmanager-service.ts, lib/services/plugins-service.ts
Allow publishing of patches in AppManager. Add new command: `appmanager livesync`. It can be used without parameters in which case the user must confirm that the patch should be published to all platforms. The command accepts multiple arguments, which are the platforms. It can be used with one or with many platforms:
* `$ appmanager livesync android`
* `$ appmanager livesync android ios`
etc.
In case LivePatch plugin is not enabled for release configuration, we notify the user the we are enabling it.
http://teampulse.telerik.com/view#/12319
=> AppManager LiveSync

lib/commands/project/init.ts, lib/project.ts, test/project.ts, test/resources/blank-NativeScript.abproject
`appbuilder init` is trying to determine project type based on the files in the current directory. As NativeScript had changed their templates we have to update our logic. Remove the check for bootstrap.js file as it is not required anymore. Fix unit tests.
=> Fix init command and unit tests

docs/man_pages/index.md
Links in markdown files should be stripped in console help. Fix the incorrect regex, so now the correct text between [ and ] will be shown.
Fixes: http://teampulse.telerik.com/view#item/290105
=> Fix markdown links in console

lib/project.ts
Mobile websites do not have configuration specific files. Executing `$ appbuilder edit-configuration -h` is trying to print list of configuration files for all frameworks. Do not print message for frameworks which do not have configuration specific files.
Fixes http://teampulse.telerik.com/view#item/289440
=> Fix dynamic help for edit-configuration command.

lib/commands/prop/prop-set.ts
`$ appbuilder prop set` should work for setting array values. Remove incorrect validation logic which was allowing only singe value to be used.
Fixes http://teampulse.telerik.com/view#item/289487
=> Allow setting of multiple values with prop set

docs/man_pages/project/testing/livesync-cloud.md, docs/man_pages/project/testing/livesync.md
NOTE: The links will not work until we have published the 2.9 docs.
=> Mentioned programmatic LiveSync. Fixed spelling for three-finger.

lib/commands/debug.ts, lib/commands/simulate.ts
Move validation logic from execute method of simulate command to canExecute in order to prevent incorrect exception when command is invoked on Linux. Use hostCapabilities as top priority when validating - if the current os does not support simulator/debugger, we should fail immediately.
Fixes http://teampulse.telerik.com/view#item/284572
=> Fix simulator error on Linux

lib/project/framework-project-base.ts
When user does not specify appid, we set default one based on appName. If the name starts with number, we should prefix the appid with "the" keyword. This was not working due to incorrect regex in our code. The regex was checking if the name contains only numbers. Fix this to check if the name starts with number.
Fixes http://teampulse.telerik.com/view#item/290326
=> Fix default appid creation

lib/project.ts
When running `$ appbuilder create website SomeName` gratuitous information about application identifiers is shown
Fixes http://teampulse.telerik.com/view#item/290638
=> Remove gratuitous information when creating website project

lib/services/appmanager-service.ts, lib/services/plugins-service.ts, test/build-configurations.ts, test/plugins-service.ts
Fix the messages shown to user when using AppManager LiveSync. Ensure user is logged in and the project type is cordova.
Make sure user is loggedIn when collecting plugins information in order to prevent output like:
```
Multiple exceptions were thrown:
Not logged in.
Not logged in.
```
=> Fix appmanager livesync messages

lib/services/plugins-service.ts
When you use `$appbuilder plugin remove <plugin> --debug` or `$appbuilder plugin remove <plugin> --release` you expect to remove the plugin only for the specified configuration. The output always shows that the plugin has been removed for both configurations, but in fact its removed only for the specified one.
http://teampulse.telerik.com/view#item/290590
=> Fix plugin remove output

docs/man_pages/project/testing/livesync-android.md, docs/man_pages/project/testing/livesync-cloud.md, docs/man_pages/project/testing/livesync-ios.md
Fix some spaces and additional symbols in livesync help, which are causing incorrect rendering of the content.
=> Fix indentation issues in livesync help

lib/services/build.ts
When you execute `$ appbuilder build <platform>` and project is using Apache Cordova 3.7.0 (or later) and WPSdk 8.0, we print warning that the user can target WPSdk 8.1
Show this warning only when building for WP8.
Fixes http://teampulse.telerik.com/view#item/290755
=> Print WP8 message only for WP8 builds

lib/commands/plugin/list-plugin.ts, lib/declarations.d.ts, lib/services/plugins-service.ts
When plugin is enabled in only one configuration (for example in release only), trying to remove it with `$ appbuilder plugin remove <pluginid>` is telling you that the plugin is not enabled for this project.
When plugin is enabled in only one configuration (for example in release only) trying to add it with `$ appbuilder plugin add <pluginid>` is adding it to both configurations, so in release config the plugin is added twice.
When plugin is enabled in only one configuration (for example in release only) trying to add it with `$ appbuilder plugin add <pluginid> --debug --release` is adding it to both configurations, so in release config the plugin is added twice.
Remove `getInstalledPluginsEnabledAtLeastInOneConfiguration` and use its logic as default for getInstalledPlugins. This way we …
=> Fix plugin add/remove

lib/hooks/typescript-compilation.ts
CLI has its own typescript definition files, which are used when we build typescript projects. Make sure to exclude them in case the project directory already has files with such name. This is the scenario with NativeScript TypeScript projects, which have android17.d.ts files in the templates and we are adding them again on build.
Fixes http://teampulse.telerik.com/view#item/290964
=> Prevent doubling of typescript definitions

lib/services/build.ts
Replace the static 'Development'
with the actual provision type used for the build
Fixes http://teampulse.telerik.com/view#item/291106
=> Change iOS build message

lib/commands/samples.ts, lib/config.ts, test/commands-service.ts
Stop execution of sample command and its subcommands for on-premise deployments
Fix unit tests which breaks newly added ones
Introduce ON_PREM configuration setting
Introduce ICommand.isEnabled property with semantics:
- when explicitly false, do not execute command
- when true or undefined, execute it
See http://teampulse.telerik.com/view#item/288143
=> Stop execution of sample commands for on-prem deploy

lib/commands/cryptographic-identities.ts, lib/definitions/cryptographic-identities.d.ts, lib/services/build.ts
In theory it is possible to build an android application
with a certificate issued by Apple Inc. however such apps
cannot actually be installed on Android devices.
Fixes http://teampulse.telerik.com/view#item/291032
=> Fail android build if iOS certificate is used

lib/commands/cryptographic-identities.ts
When a wrong password is explicitly provided do not
attempt to import the certificate three times.
Instead prompt user for a new password
Fixes http://teampulse.telerik.com/view#item/291232
=> Fix triple import certificate attempt

docs/man_pages/lib-management/update-kendoui.md, lib/commands/update-kendoui.ts, lib/options.ts
Improve update-kendoui command to accept several -- options:
* `--verified` - lists verified plugins
* `--core` - lists core plugins
* `--professional` - lists professional plugins
They can be combined, but core and professional cannot be used simultaneously. For example `$ appbuilder update-kendoui --core --verified` will list only verified core plugins.
Add `--latest` option. If it is specified, the user will not be prompted to select version, but the latest available version will be installed. This option can be combined with the other options. for example:
* `$ appbuilder update-kendoui --verified --latest` will install latest available verified version
* `$ appbuilder update-kendoui --verified --core --latest` will install latest available verified core version …
=> Improve update-kendoui command

lib/json-schema/json-schema-validator.ts
When trying to show error from JsonSchemas and the property is not part of Base schema, an error is raised (Cannot read property 'errorMessage' of undefined).
Add check if the property is part of the schema.
Fixes http://teampulse.telerik.com/view#item/290863
=> Fix error when printing errorMessage from json schemas

lib/json-schema/json-schema-validator.ts
In case the property does not have error message, we do not print correct error. For example try `$ appbuilder prop set Framework Cordova` inside NativeScript project.
=> Fix error messages printing

publish.cmd
Use release branch to tag the latest version.
Invoke `npm publish`
=> Fix publish script

lib/commands/update-kendoui.ts
When user cannot use professional versions and tries to execute `appbuilder update-kendoui --professional --latest` leads to `Cannot read property 'DownloadUrl' of undefined`
The problem is that packages collection that we are using becomes empty and we are trying to get the first item of it (undefined), so it does not have DownloadUrl property.
Prevent this case by checking the length of packages collection and show correct error message in case --professional is specified.
Fixes http://teampulse.telerik.com/view#item/291742
=> Fix update-kendoui --professional --latest

lib/services/appmanager-service.ts
Fix upload of nativescript projects to appmanager. The issue is raised from resolving `pluginsService` in the constructor of AppmanagerService. PluginsService constructor is failing when the project is **NOT** Cordova.
Use injector to resolve pluginsService only where it is required.
Fix error when plugin is enabled manually in configuration, but we are unable to find it in marketplace (for example manually add com.telerik.LivePatch in release config and try $ appbuilder appmanager livesync android with user who does not have access to this feature. You'll receive error **Cannot read property data of undefined**
Fixes http://teampulse.telerik.com/view#item/291755
=> Fix upload of nativescript projects to appmanager

lib/bootstrap.ts, lib/project.ts, lib/project/project.d.ts, lib/services/plugins-service.ts, test/plugins-service.ts, test/stubs.ts
Make sure plugin with different versions is not enabled in different configurations (ask the user to select which version to use in this case - list all available versions).
The following behavior should be accomplished with this fix for marketplace plugins:
In **interactive terminal** when version of plugin is specified (`$ appbuilder plugin add toast@2.0.4`):
precondition(below) \ users option -> | `--debug` | ` --release` | `--debug` and `--release` (or neither of them)
--- | --- | --- | ---
plugin is enabled in all configs with same version | prompt for action | prompt for action | update version
plugin is enabled in one config (`debug`) | update version in this config only | prompt for action | update version
plugin is enabled in all configs with different versions | prompt for …
=> Fix marketplace plugins commands

lib/services/plugins-service.ts, test/plugins-service.ts
If an invalid plugin is installed in either build configuration (regardless whether the users just modified the file themselves or something just went wrong) an error should be thrown indicating that this plugin is not eligible
Fixes http://teampulse.telerik.com/view#item/291777
=> Fix no error when invalid plugin installed

lib/config.ts, lib/declarations.d.ts, lib/services/samples-service.ts, test/stubs.ts
When we call api.github.com, there are some limitations. In order to bypass them, we have to pass access token to the call. Take it from ~/.abgithub file and add it to our "samples" calls.
More info here http://teampulse.telerik.com/view#item/291726
=> Use access_token for samples

lib/commands/prop/prop-print.ts, lib/declarations.d.ts, lib/project.ts, lib/project/project.d.ts, lib/services/project-properties-service.ts, test/project.ts
In case you try `$appbuilder prop set CorePlugins A B C --debug` the value of CorePlugins will be modified in .abproject instead of .debug.abproject file. Fix this behavior by passing configurationSpecificData to updateProjectProperty method and modify it instead of the projectData.
In case user had not specified --debug or --release flag (`$appbuilder prop set CorePlugins A B C`, we will update the .abproject, but when the app is built, this value will be overwritten by the value in the configuration specific file. Add removeProjectProperty method to ProjectPropertiesService, so when user modifies any property in .abproject, the value in the configuration files will be removed. This way the build will use the correct data from .abproject.
Fix printing of properties inside project dir to …
=> Allow modification of CorePlugins in configuration specific files

lib/services/plugins-service.ts, test/plugins-service.ts
When plugin configure is called for plugin, which is not installed, it automatically adds the plugin to your project. We already have the validation implemented, but after one refactoring, the isPluginInstalled method was returning incorrect result.
Added unit tests for isPluginInstalled method.
Update to latest common lib where definitions of semver had been updated.
=> Fix plugin configure

docs/man_pages/lib-management/plugin-add.md, lib/declarations.d.ts, lib/options.ts, lib/plugins-data.ts, lib/services/marketplace-plugins-service.ts, lib/services/plugins-service.ts
Add support for installing the latest plugin version. The command is: `$ appbuilder plugin add toast --latest`. This will install the latest available version of Toast plugin.
Add support for installing the default plugin version. The command is: `$ appbuilder plugin add toast --default`. This will install the default version of Toast plugin.
As on the server MarketplacePluginVersionsData has three more properties, which are not generated in our server-api, implement IMarketplacePluginVersionsData interface, that extends this class and add the properties there.
http://teampulse.telerik.com/view#item/292306
=> Add latest or default plugin versions

lib/project/framework-project-base.ts, test/resources/blank-Cordova.abproject, test/resources/blank-NativeScript.abproject
When a new Cordova project is created, we have to set its Description to be equal to projectName. This is due to this change: https://github.com/Icenium/Ice/pull/3729
This will fix our unit tests.
> NOTE: The change on the server reflects only Cordova projects, but it will be changed to update NativeScript project's descriptions as well.
=> Set Description when creating new project

.gitignore, docs/man_pages/project/configuration/mobileframework-set.md, docs/man_pages/project/configuration/mobileframework.md, lib/bootstrap.ts, lib/commands/dev/prepackage.ts, lib/commands/framework-versions/print-versions.ts, lib/commands/framework-versions/set-version.ts, lib/declarations.d.ts, lib/hooks/typescript-compilation.ts, lib/project.ts, lib/project/cordova-project.ts, lib/project/nativescript-project.ts, lib/project/project.d.ts, lib/project/web-site-project.ts, lib/resource-loader.ts, lib/server-api.d.ts, lib/server-api.ts, lib/services/cordova-migration-service.ts, lib/services/nativescript-migration-service.ts, resources/project-properties-nativescript.json, test/framework-versions.ts
When the project is migrated we have to update tns_modules directory and .abproject with the new version of the project. Add new NativeScriptMigrationService and use it with dynamic call to upgrade the project. In case an error occurs during migration, rollback the migration. In case current project version is not supported, we have to break the migration. Oboslete versions can still be build, but we cannot migrate them.
Download NativeScript migration data during prepublish. Make sure to save supportedVersion in format - DisplayName(string) and Version(string).
You can change the version by using: `$ appbuilder prop set FrameworkVersion 1.0.1` (or 0.10.0) or `$ appbuilder mobileFramework set 1.0.1`
You can list valid versions by using `$ appbuilder prop print FramworkVersion …
=> Allow migration of NativeScript projects

lib/services/cordova-migration-service.ts, test/resources/blank-NativeScript.abproject
`appbuilder mobileframework` lists the supported versions of Cordova framework. Currently our server supports Cordova 2.7.0 (marked as deprecated), but CLI requires at least 3.0.0. Executing the command `appbuilder mobileframework` insider Cordova project lists version 2.7.0. The problem is in the Cordova migration data file, where we are not filtering versions below 3.0.0. Fix this by filtering the versions and add save in the file only the supported versions.
=> Show only supported versions for Cordova

lib/declarations.d.ts, lib/project.ts, lib/services/project-properties-service.ts, test/project.ts
Old PR -> https://github.com/Icenium/icenium-cli/pull/1068
CorePlugins could be part of .debug.abproject, .release.abproject and .abproject. Make sure `prop` related commands will do the same as our UI Clients:
* When CorePlugins in debug and release are the same, move them to .abproject.
* When a plugin is added/removed for only one configuration, move all plugins to configuration specific files and modify the one, specified by user.
* When prop set is used without configuration flag (--debug or --release), remove the CorePlugins from configuration specific files and set them in .abproject.
* When Core Plugins are different in each configuration and user had not specified configuration flag for operation, execute it on all available configs.
* When different plugins are available in …
=> Update CorePlugins in all config files

lib/services/cordova-plugins.ts, test/plugins-service.ts
Currently our server never returns information about LivePatch plugin. As a workaround - add the information in getAvailablePlugins. This way you can add the plugin. In case you try publishing LivePatch (`$ appbuilder appmanager livesync android` for example), the server will check if you are able to use this feature and will fail in case you are not.
Remove the HACK when server is working correctly.
http://teampulse.telerik.com/view#item/292698
=> Add LivePatch to available plugins

lib/project.ts
When property is not array and configuration specific flag is used for prop print command, the value of the property is not shown in the output.
Also if the property does not have value in configuration specific data and user wants to see only this configuration, we should not show empty table for this property.
Fixes http://teampulse.telerik.com/view#item/292902
=> Fix prop print for properties which are not arrays

docs/man_pages/publishing/appmanager-groups.md, docs/man_pages/publishing/appmanager-livesync.md, docs/man_pages/publishing/appmanager-upload-android.md, docs/man_pages/publishing/appmanager-upload-ios.md, docs/man_pages/publishing/appmanager-upload-wp8.md, docs/man_pages/publishing/appmanager-upload.md, docs/man_pages/publishing/appmanager.md, docs/man_pages/publishing/appstore-list.md, docs/man_pages/publishing/appstore-upload.md, docs/man_pages/publishing/appstore.md, docs/man_pages/publishing/certificate-create-self-signed.md, docs/man_pages/publishing/certificate-export.md, docs/man_pages/publishing/certificate-import.md, docs/man_pages/publishing/certificate-remove.md, docs/man_pages/publishing/certificate-request-create.md, docs/man_pages/publishing/certificate-request-download.md, docs/man_pages/publishing/certificate-request-remove.md, docs/man_pages/publishing/certificate-request.md, docs/man_pages/publishing/certificate.md, docs/man_pages/publishing/provision-import.md, docs/man_pages/publishing/provision-remove.md, docs/man_pages/publishing/provision.md, lib/declarations.d.ts, lib/options.ts, lib/server-api.d.ts, lib/server-api.ts, lib/services/appmanager-service.ts, package.json
AppManager now supports public app distribution. 
Public option is suitable if your application already has built-in authentication mechanism or if you want to grant anonymous access to your app.AppManager user credentials will not be required to download the app.
Use private option (public not set) if you want AppManager to restrict the access to your application. AppManager user credentials will be required to download the app (the usual flow, only users in the groups can download the app)
=> Add 'public' option to AppManager upload command

lib/commands/framework-versions/print-versions.ts, lib/services/nativescript-migration-service.ts
When project is using obsolete NativeScript version and user tries to execute **$ appbuilder mobileframework** inside project dir, an error message is shown: "Cannot find version <v> in the supported versions." Change this to explanation that the current version is obsolete and the project cannot be migrated, but we can still build it.
Fixes http://teampulse.telerik.com/view#item/292936
=> Show more descriptive error for obsolete {N} projects

lib/services/build.ts
When building for iOS with `--download` a QR code cannot be generated so there's no point in a warning message
Fixes http://teampulse.telerik.com/view#item/292777
=> Fix warning message when building with --download

config/dependency-config.json, lib/declarations.d.ts, lib/services/screen-builder-service.ts
Fixes http://teampulse.telerik.com/view#item/292965
=> Get all supported sb commands from .schema.json instead calling screenBuilder's listGenerators endpoint

lib/services/plugins-service.ts
Currently LivePatch plugin is added to debug config instead of release. This is due to mistake in the code, which is setting configurations variable to be the forbiddenConfig. Fix this code.
=> Add LivePatch plugin to release only

lib/project/nativescript-project.ts, lib/project/project-constants.ts, lib/project/project.d.ts, lib/services/nativescript-migration-service.ts
App_Resources directory of NativeScript projects should be part of app directory. In 0.10.0, this directory was on the same level as app directory. Make sure to move it under app directory during project migration.
When checking all platform assets, make sure to update correct App_Resources directory. If the project is not 0.9.0 and ther's no App_Resources directory inside app directory, check for existing of App_Resources in the upper level and modify the App_Resoureces there.
Part of http://teampulse.telerik.com/view#item/293294
=> Migrate App_Resources directory in {N} projects

lib/commands/dev/prepackage.ts, lib/declarations.d.ts, lib/project/cordova-project.ts, lib/project/nativescript-project.ts, lib/project/project-constants.ts, lib/project/project.d.ts, lib/resource-loader.ts, lib/services/nativescript-migration-service.ts, lib/templates-service.ts
Currently we have App_Resources in our resources folder. It is created on dev-prepackage command by extracting App_Resources directory from Cordova.Blank template. Now we need App_Resources for NativeScript projects. With the new templates, the App_Resources folder is under app folder of {N} templates. In order to handle this, I've modified templatesService unpackAppResources to extract cordova and ns App_Resources.
Move App_Resources folder to be under Cordova and NativeScript directories. Also with the old code, we had App_Resources/App_Resources/Android..., now we have Cordova/App_Resources/Android...
Change the name of NATIVESCRIPT_APP_RESOURCES_DIR_NAME to APP_RESOURCES_DIR_NAME as this name is not specific for NativeScript projects.
Replace appResourcesDir property of resources with …
=> Use correct App_Resources

package.json
Currently our unit tests cannot be started on Windows as the .bin/_mocha file is shell script and some of its symbols cannot be resolved. Replace the call with call to javascript file.
=> Fix test command in package.json

lib/declarations.d.ts, lib/services/cordova-migration-service.ts, lib/services/plugins-service.ts, test/cordova-migration-service.ts, test/plugins-service.ts, test/project.ts
In case plugin requires Cordova 3.5.0, but current project targets 3.2.0, adding such plugin will break the build. Prevent this by removing such plugins from getAvailablePlugins result. This will also hide the plugin from `appbuilder plugin --available` output.
Add unit tests for the result of getAvailablePlugins and for livePatch plugin.
Fixes http://teampulse.telerik.com/view#item/292103
=> Filter plugins not supported for projects Cordova version

docs/man_pages/lib-management/plugin-add.md, docs/man_pages/lib-management/plugin-configure.md, lib/declarations.d.ts, lib/options.ts, lib/services/plugins-service.ts, test/plugins-service.ts
When you want to automate plugin add, there's no way to automate the process of adding CordovaPluginVariables and prompter is shown for each of them. In order to simplify this, add `var` dashed option, which should work in the following way:
* `$ appbuilder plugin add dropbox --var.APP_KEY 1 --var.APP_SECRET 2` - sets the plugin variables APP_KEY to 1 and APP_SECRET to 2 in all configurations
* `$ appbuilder plugin add dropbox --var.debug.APP_KEY 1 --var.debug.APP_SECRET 2 --var.release.APP_KEY 3 --var.release.APP_SECRET 4` - in .debug.abproject sets APP_KEY to 1 and APP_SECRET to 2 and in .release.abproject sets APP_KEY to 3 and APP_SECRET to 4
* `$ appbuilder plugin add dropbox --var.APP_KEY 1 --var.APP_SECRET 2  --var.debug.APP_KEY 3` - in .debug.abproject sets APP_KEY to 3 and …
=> Pass CordovaPluginVariables on the command line

lib/declarations.d.ts, lib/options.ts
Client option was used in analytics tracking only, but it has been replaced there, so we do not need it anymore.
=> Remove client option and fix analytics tracking

lib/services/plugins-service.ts, test/plugins-service.ts
In case a plugin has variable with dot ("."), you cannot pass it on the command line with --var option as each dot is converted to new inner object by yargs. Bypass this behavior, by converting the yargs object to one that matches our required behavior.
Add unit tests.
=> Parse --var option when variable has dots

lib/commands/cloud-projects.ts, lib/declarations.d.ts, lib/server-api.d.ts, lib/server-api.ts, lib/services/remote-projects-service.ts, lib/swagger/service-contract-generator.ts, test/cloud-projects.ts, test/remote-projects-service.ts
Our code is always exporting the first project in a solution. Also the endpoint which we are using does not exist anymore.
Use the new endpoint and modify the behavior in the following way:
* `$ appbuilder cloud` - prompts you to select solution for which to list the projects
* `$ appbuilder cloud Sln1` - lists projects of Sln1 solution
* `$ appbuilder cloud 1` - lists projects of the first solution listed by `$ appbuilder cloud`
* `$ appbuilder cloud export` - prompts to select solution from which to export project. If the selected solution has only one project - directly export it. In case the solution does not have any projects - show error. In case the project has more than one project - prompt the user to select one of the projects and after that export it.
* `$ appbuilder cloud …
=> Export projects from the cloud

docs/man_pages/lib-management/plugin-add.md, docs/man_pages/lib-management/plugin-configure.md
When reviewing this, keep in mind the following:
* There is a known issue that Rosko has committed to fix. In some cases, the CLI shows `[*` instead of the expected `*`.
* I have deliberately dropped or avoided explanations of the various `--configuration` and `--var.configuration` combos since this is not a scenario that we want to advertise. Users should use either `--configuration --var` or just `--var.configuration` to set something in a particular configuration.
* Currently, if you have enabled a plugin in one configuration but run `plugin configure --var.the-other-configuration` or `plugin configure --var` we enable the plugin for the other configuration as well. This is an erroneous behavior and will be fixed.
=> Introducing --var

docs/man_pages/project/creation/create-screenbuilder.md, docs/man_pages/project/creation/create.md, lib/bootstrap.ts, lib/commands/debug.ts, lib/commands/project/create.ts, lib/commands/simulate.ts, lib/declarations.d.ts, lib/options.ts, lib/project.ts, lib/services/simulatorPlatformServices.ts, lib/services/simulatorService.ts, test/build-configurations.ts, test/common-options.ts
Includes some refactoring (introduction of a new service) , a minor bug fix (caching of the project directory) and an option to prevent simulator from launching
Implements [this story](http://teampulse.telerik.com/view#item/293551)
Merge after https://github.com/telerik/mobile-cli-lib/pull/365
=> Launch simulator after creating a ScreenBuilder project

package.json, test/commands-service.ts, test/common-options.ts, test/plugins-service.ts, test/project.ts, test/publish-service.ts, test/stubs.ts
Each command can use specific dashed options (`-- avd <name>` for example is valid for one command, but not for other). Add dashedOptions parameter to ICommand interface and make sure to use it for validation when it exists. In case there's no dashedOptions paramter, use the common options.
Use correct types for yargs - "string", "boolean", etc. instead of 0, 1, 2 which were the result of our enum. Replace the enum with class and remove code, which we do not need anymore as yargs is doing its work as expected.
After yargs is updated to latest version, some fixes have to be applied - now when `yargs.options(opts).argv` is passed, it returns all members of `opts`, but the ones that are not part of process.argv have value undefined.
Fix unit tests based on the changes and remove some, which …
=> Add dashedOptions for each command

lib/commands/dev/prepackage.ts
The package that is prepared for upload in npm contains coverage dir which is created as an output of the execution of our unit tests. Remove this dir during packaging resources for npm.
http://teampulse.telerik.com/view#item/296352
=> Remove coverage dir from appbuilder package

lib/commands/project/create.ts
When you create SB project and for some reason starting the simulator fails, the project is deleted. Make sure the start the simulator outside of the try-catch, so even if it fails, the project will not be deleted when the simulator fails.
Fixes http://teampulse.telerik.com/view#item/296228
=> Fix creation of SB when simulator start fails

Gruntfile.js, lib/config.ts, test/stubs.ts
npm 2.11.2 introduced and issue when the version in package json has "-". Such packages cannot be installed directly from npmjs.org.
Fix this by adding buildVersion property in our package.json and set there the build number from Jenkins. This way the version in package.json will remain correct. Add "setPackageName" grunt task, which renames the `appbuilder-<version>.tgz` to `appbuilder-<version>-<buildVersion>.tgz`
=> Use correct semver version in package.json

lib/commands/emulate.ts
Emulate commands should ensure all platform assets before execution. Also make sure a project is found before emulating.
Fixes http://teampulse.telerik.com/view#item/296214
=> Ensure platform assets before emulate

lib/service-util.ts
CLI has built-in mechanism for checking if the current version is the latest one. If it is not, CLI does not execute you any http requests (almost all commands have such requests). For OnPremise we do not want this check, so make sure to skip this behavior.
Fixes http://teampulse.telerik.com/view#item/296618
=> Do not require latest version for OnPremise

lib/server-api.d.ts, lib/server-api.ts, lib/swagger/service-contract-generator.ts, lib/swagger/swagger.d.ts
Includes fixes for two bugs
* if an enum is encountered an even amount of numbers on a given endpoint definition it is not added to the end .d.ts result
* if an enum is encountered in multiple endpoint definition it is added as a duplicate
=> Fix swagger not generating enums properly

.settings/launch.json, .settings/settings.json
- Fix behavior that is trying to login the user when tracking command - in fact we should first check if the user is logged in and if not, do not try to login.
- Make sure commands are tracked, but for some of them we should not ask the user for confirmation of usage reporting (for example help command). So add new command property - `disableAnalyticsConsentCheck` and set it to true for help, usage-reporting and error-reporting commands. Make sure to prevent commandsService for checking the consent when this property is true.
=> Fix analytics issues

lib/commands/cloud-projects.ts, lib/declarations.d.ts, lib/services/remote-projects-service.ts, test/cloud-projects.ts, test/remote-projects-service.ts
According to our discussions, we would like to be able to export full solutions, not only one project. So the behavior of `appbuilder cloud export` command should be:
* `$ appbuilder cloud export` - prompts to select solution from which to export project. After solution is selected, prompt the user to select project. In this prompt there's option - export solution, when it is used, the full solution is exported.
* `$ appbuilder cloud export Sln1` - Exports the whole solution. In case the solution does not have any projects - show error.
* `$ appbuilder cloud export 1` - Exports the selected solution (first project listed by `$ appbuilder cloud`). In case the solution does not have any projects - show error. 
* `$ appbuilder cloud export Sln1 Proj1` - Exports Proj1 of Sln1. If any of them …
=> Export solutions

lib/project.ts
When running `$ appbuilder prop add` or any other prop-related command without a property name the message Invalid property name 'undefined' is displayed.
Fixes http://teampulse.telerik.com/view#item/297059
Retarget from https://github.com/Icenium/icenium-cli/pull/1155
=> Fix Invalid property name 'undefined' message

lib/commands/project/create.ts, lib/services/screen-builder-service.ts
Upon a failure in any screenbuilder command an error object is thrown which contains multiple levels of nested errors. We should print all of the errors' messages instead of just root-level ones.
Fixes [#296877](http://teampulse.telerik.com/view#item/296877)
=> Print all error messages upon screenbuilder failure

lib/options.ts
On Mac and Linux, move SB cache under sb directory. This will fix the issue that during first downloading of ScreenBuilder, CLI is deleting its own cache and after that a browser is opened, waiting for login information.
Fixes http://teampulse.telerik.com/view#item/297519
=> Move screebuilder cache under sb directory

lib/project/nativescript-project.ts, lib/project/project-files-manager.ts
Fix editing of AndroidManifest and Info.plist for {N} projects. Currently we were creating them on the root level, but they should be inside app/App_Resources dir.
Fixes http://teampulse.telerik.com/view#item/297518
=> Fix editing of config files for {N} projects

lib/commands/appmanager-livesync.ts, lib/commands/appmanager.ts, lib/commands/build.ts, lib/commands/deploy.ts, lib/commands/emulate.ts, lib/commands/live-sync.ts, lib/project/cordova-project.ts
WP8 related commands should be disabled for On Premise. Disable the following commands:
* `appmanager upload wp8`
* `build wp8`
* `deploy wp8`
* `emulate wp8`
* `livesync wp8`
Change `appbuilder appmanger livesync` command to exclude WP8 when listing available platforms. Also check if the user had specified WP8 platform, for example:
`appbuilder appmanger livesync android wp8` and fail if we are in On Premise scenario.
Do not allow editing of wp8-manifest and wp8-config files in OnPremise scenario.
Fixes http://teampulse.telerik.com/view#item/297596
=> Disable WP8 related commands for OnPremise

lib/services/project-properties-service.ts
Yargs will parse all non-hyphenated values as strings in case we tell we want this. So, let's declare we want this and remove our hack, that's doing it. This will also fix the case when numbers like 8.0 are passed on the console. Yargs is giving them to us as "8", but we need the full value. With this fix, we'll receive "8.0".
Remove the hack for WPSdk property as it is not required anymore.
The fix is required for http://teampulse.telerik.com/view#item/296803
=> Parse command line values as strings

lib/commands/build.ts
When build command is executed outside of project dir, its execute logic is triggered and the hook that's attached to it is throwing an error. This error is caught by our uncaughtException listener, which prints message with call stack and exits the process. We have catch for this code, but it loosk like the problem is with the two fibers working in parallel.
**Also update common  lib, where the following change is applied:**
In case command does not have default command and arguments are not passed, we are trying to execute default command, which is not expected. Make sure not to return true in this method, when there's no default command.
Fixes: http://teampulse.telerik.com/view#item/297504
=> Fix error message of build commands

lib/commands/deploy.ts, lib/declarations.d.ts, test/project.ts
When iOSDeploymentTarget is set to 8.4 for example, but user is trying to deploy on iOS device with 8.1.2, we must fail as different issues occur (on Windows we say "Successfully deployed", but nothing is deployed, while on Mac the deployment freezes). Fix this behavior by showing error when device's OS is with lower version, but you can still deploy on other iOS devices.
Fixes http://teampulse.telerik.com/view#item/297476
=> Prevent deploy on iOS device with lower iOSDeploymentTarget

lib/commands/emulate.ts
In case user does not have Android SDK installed, we are trying to execute adb from CLI resources. This fails in case `$ <CLI> device` command or `$ <CLI> deploy <platform>` is executed as the "exec" cannot resolve the path with spaces.
Also fix the check dependencies of AndroidEmulatorService in order to fail with correct error message when something is not configured properly (currently it is failing with ENOENT error).
Fixes http://teampulse.telerik.com/view#item/297604
=> Fix adb spawn when path contains spaces

lib/services/path-filtering.ts, test/path-filtering.ts
For example, test patern test/\*\*/\* must exclude test/.file
Fixes http://teampulse.telerik.com/view#item/297858
=> When evaluating glob patterns with wild cards do not skip .files

lib/commands/deploy.ts
We should not validate iOSDeploymentTarget when this property is not set in .abproject (it is not mandatory).
Fixes http://teampulse.telerik.com/view#item/297931
=> Fix deploy on iOS devices

lib/services/build.ts
When some not mandatory property (like WP8SupportedResolutions) is not defined in .abproject, json schema validation is correct, but we have additional check for our build properties which is preventing the build. Show warning instead of error in such case as the json validation will fail long before that if mandatory property has value undefined.
Fixes http://teampulse.telerik.com/view#item/298156
=> Do not fail when build property is not defined

lib/validators/cryptographic-identity-validators.ts
When building for Android AppStore, Google requires min endDate of the certificate to be 23 October 2033. When you have certificate expiring exactly at this date, CLI does not use it and tells you that it cannot find applicable store certificate.
The problem is that our constant for MIN expiration date of the certificate is created with Date only. This creates new Date object with specified date, but the hours in the object depend on the current timezone, so for BG it is set to 3:00:00. So when we validate the certificates expiring at 00:00:00 on 23 October 2033, we do not use them as they are not matching the MIN expiration date.
Fixes http://teampulse.telerik.com/view#item/298197
=> Fix finding of Google Play certificate

lib/services/extensions-service-base.ts
Instead of checking for a newer version, check if cached version differs from the one the cli is looking for.
Fixes [#298255](http://teampulse.telerik.com/view#item/298255)
Ping @rosen-vladimirov @teobugslayer
=> Fix screenbuilder update logic

lib/declarations.d.ts, lib/services/build.ts
The server will start returning multiple build result files. The app package is marked with disposition 'BuildResult', while additional configuration files with 'AdditionalFile'.
We need to download the additional files when --download option is specified, but should not generate a QR code for them.
ping @Fatme @rosen-vladimirov @teobugslayer 
refs https://github.com/Icenium/Ice/pull/4204, http://teampulse.telerik.com/view#item/300733
=> Generate QR codes only for application packages

lib/services/build.ts
Respect the settings object instead of hardcoding AdHoc type provisions.
Kudos for @galexandrov for discovering the bug.
=> Fix provision autoselection upon build

README.md
We need to have this in the master as this is our landing spot in GitHub. We need to fix this readme as soon as we introduce Node 4.x support.
=> Fixed sys reqs until we introduce support for Node 4

config/dependency-config.json, docs/man_pages/index.md, docs/man_pages/screenbuilder/add-about.md, docs/man_pages/screenbuilder/add-authentication.md, docs/man_pages/screenbuilder/add-dataprovider.md, docs/man_pages/screenbuilder/add-field.md, docs/man_pages/screenbuilder/add-form.md, docs/man_pages/screenbuilder/add-list.md, docs/man_pages/screenbuilder/add-view.md, docs/man_pages/screenbuilder/screenbuilder.md, docs/man_pages/screenbuilder/upgrade-screenbuilder.md, lib/bootstrap.ts, lib/commands/project/create.ts, lib/commands/upgrade-screenbuilder.ts, lib/declarations.d.ts, lib/services/screen-builder-service.ts
Includes
+ Backwards compatibility with projects, created with earlier Screen Builder versions
+ An option to explicitly upgrade an existing project - **new command**
+ Help for the new command
+ A prompt upon executing any Screen Builder-related command in an old project of whether or not to upgrade the project's Screen Builder version. Should the user choose to upgrade, the original command is automatically executed afterwards
+ Apparently Screen Builder now releases the console after a successful command's execution
+ Minor refactorings and fixes in the ```screen-builder-service.ts```
Depends on https://github.com/telerik/mobile-cli-lib/pull/450
Implements [Integrate with new Screen Builder latest release](http://teampulse.telerik.com/view#item/298407)
And fixes [Error on add-field if …
=> Integrate screenbuilder v0.0.10

lib/services/image-service.ts
Server's response was altered a bit in https://github.com/Icenium/Ice/pull/4206. Conform CLI with new server response
Implements/fixes [#299047](http://teampulse.telerik.com/view#item/299047)
=> Conform image generation with server

lib/services/livesync-service.ts
Remove a parameter that is no longer used in common's master branch from
livesync service.
=> Fix Livesync service

lib/services/image-service.ts
Due to backwards compatibility issues, App_Resources folder will not be removed from the result archive and changes made because of this need to be reverted.
Reference: https://github.com/Icenium/Ice/pull/4330
Ping @rosen-vladimirov 
This change fully reverts https://github.com/Icenium/icenium-cli/commit/3ec1bbb51e38dfa71934e38560d59e4c15b20f4f
=> Revert App_Resources fix

lib/commands/kendoui-base.ts, lib/commands/kendoui-install.ts, lib/commands/kendoui-notes.ts, lib/declarations.d.ts, lib/services/kendoui-service.ts
Includes fixes for
+ Package listing does not respect the `--latest` tag
+ Error handling rather than prompt whenever zero packages meet certain conditions (e. g. `$ appbuilder notes --verified`)
+ Prompt for release note review upon installation with `--latest` tag. **Note:** this prompt can be avoided by setting the --force tag
+ Show package version after successful package installation
Fixes [kendo critical bug](http://teampulse.telerik.com/view#item/301864)
=> Fix kendoui command-related bugs

lib/services/nativescript-project-plugins-service.ts
Add quotes around name when searching the npm - this will make the search stricter. For example when registry-validator is checked, npmsearch api will find everything that has validator in it in case the quotes are missing.
=> Make npmsearch stricter

lib/commands/plugin/find-plugins.ts, lib/services/nativescript-project-plugins-service.ts
Plugin find command must show intersection of all provided parameters.
Also use encodeUriComponent for all parameters that user will fill when calling npmsearch.
Add error message when we cannot find any plugin matching provided arguments.
=> Use intersection for plugin|find command

lib/services/nativescript-project-plugins-service.ts
Ignore npm scripts when installing {N} plugins/npm modules to temp
directory as they may cause unexpected behavior or client's machines.
Fixes:
```
appbuilder plugin add https://github.com/rosen-vladimirov/NativeScriptPluginTest/tarball/master
```
which throws `ENOENT error`.
=> Ignore npm scripts of {N} plugins

lib/services/livesync-service.ts
In order to work correctly for added files we've changed the usage of gaze module - https://github.com/telerik/mobile-cli-lib/blob/master/services/usb-livesync-service-base.ts#L106. This requires to change the passed watch glob from cli.
If livesync --watch command is executed only the first sync works correctly. After that the changes aren't reported from the watch.
=> Use correct watchGlob

lib/commands/project/init.ts, test/project.ts, test/resources/blank-NativeScript.abproject
Currently `appbuilder init` command checks that the project has `app/tns_modules` dir.
We do not have such directory anymore, so check the `package.json` instead of it.
Fix unit tests.
=> Fix init command for NativeScript projects

lib/bootstrap.ts, lib/commands/framework-versions/print-versions.ts, lib/commands/framework-versions/set-version.ts
`$ appbuilder mobileframework` should work in the same way as `$ appbuilder prop print FrameworkVersion`
Same is valid for `$ appbuilder mobileframework set <version>` and `$ appbuilder prop set FrameworkVersion <version>`.
In order to achieve this, register new commands - `prop|print|frameworkversion` and `prop|set|frameworkversion`.
=> Unify mobileframework and prop <subcommand> FrameworkVersion commands

lib/declarations.d.ts, lib/services/nativescript-migration-service.ts, test/file-system.ts, test/stubs.ts
Due to bug in {N} 0.4.2 in our templates we have `AppResources/Android/values/styles.xml`
and `AppResources/Android/values-v21/styles.xml` files. When migrating to 1.4.3 or later,
we must remove these files as they are change in {N} android runtime.
The real styles will be taken during build.
Add unit test for renameIfExists method of fs.
http://teampulse.telerik.com/view#item/303971
=> Delete styles.xml when migrating to {N} 1.4.3+

.gitignore, lib/hooks/before-build.js, lib/hooks/before-build.ts, lib/hooks/before-deploy.js, lib/hooks/before-deploy.ts, lib/hooks/before-livesync.js, lib/hooks/before-livesync.ts
Due to changes in hooks service, our current code is trying to execute both `.ts` and `.js` hook files.
As the `.ts` do not contain any TypeScript specific logic, just remove them and use the `.js` directly.
=> Fix appbuilder hooks

lib/bootstrap.ts, lib/services/doctor-service.ts, lib/sys-info.ts
Introduce SysInfo class that extends SysInfoBase from common lib.
This class holds AppBuilder specific implementation of gathering SysInfo.
=> Introduce SysInfo class

lib/bootstrap.ts, lib/commands/cloud-projects.ts, lib/declarations.d.ts, lib/server-api.d.ts, lib/server-api.ts, lib/service-util.ts, lib/services/remote-projects-service.ts, test/cloud-projects.ts, test/remote-projects-service.ts, test/service-util.ts
Due to changes in Server API, we have to allow exporting of apps and solutions.
In order to get projects from apps, we should call TAP endpoint.
For not migrated projects we should call the old server endpoint.
The export procedure requires calling same endpoint for migrated and not migrated projects.
When exporting old projects (from solutions), we should pass the solution name as appId and send the magic Header in the request.
When exporting new projects (from apps), we should pass real appId and DO NOT send the magic Header.
In order to achieve this, introduce new class - ServiceProxyBase and use it for TAP requests.
Introduce AppBuilderServiceProxy class that extends ServiceProxyBase and register it as "serviceProxy", so we'll keep current behavior for server calls.
Add new method in …
=> Allow export of apps and solutions using new server API

lib/providers/device-app-data-provider.ts, lib/services/livesync-service.ts
Includes
+ Fixing for QR code generation for {N} Ion
+ Fix for cable LiveSync for both Cordova and {N}
After this commit every kind of LiveSync works as expected with the following limitation. **When one deploys code directly to any companion app without first scanning a QR code no subsequent cloud LiveSync-ing will work in said companion app.** This limitation comes from the fact that whenever cable LiveSync-ing to a companion app the companion app is only told to get the files and refresh - no livesync url is provided. In order to obtain a LiveSync url on the other hand, one must scan a QR code.
TP Refs: 
+ [Build android --companion generates an invalid QR code](http://teampulse.telerik.com/view#item/304910)
+ [Impossible to cloud livesync if initially cable …
=> Fix livesync

package.json
Get back the message that reports successful deploy on android device. We've deleted it a couple of commits ago.
Set version to 3.0.0
=> Show message after successful deploy on android 

lib/services/remote-projects-service.ts, test/cloud-projects.ts, test/remote-projects-service.ts
In case the user is not allowed to migrate his projects to apps, we shouldn't show NOT MIGRATED string when listing them.
Fixes http://teampulse.telerik.com/view#item/305450
=> Do not show NOT MIGRATED string when user cannot migrate

lib/services/remote-projects-service.ts
When export solution by index is called, we use helpers.findByNameOrIndex method.
This is not correct, as the method is sorting the the provided collection, so if index is used, it is not the one that user specified.
Fixes http://teampulse.telerik.com/view#item/305538
=> Fix solution export by index

package.json
Add support for node 5.1.x by updating references to native dependencies.
Add versions between 5.1.x and 6.0.0 as validated (we will not show warning for them).
The main problem with node 4.2.1 and 4.2.2 is that our prompter does not work as expected (arrow keys are not functioning). Node 5.1.0 fixes this behavior.
=> Add support for node 5.1.x

lib/definitions/plugman.d.ts, lib/services/cordova-plugins.ts, package.json
Fix support for node 5.1.0. Curently the installation is failling because we are using old plugman.
This old plugman depends on very old version of npm. During installation with npm 3.3.11 or later, the plugman fails.
This is a bug in npm itself (https://github.com/npm/npm/issues/10234). However updating our version of plugman is fixing the installation.
The new plugman had change the callback parameters - previously it was one parameter, now it has two - error and result.
Fix our callbacks to have two arguments.
=> Fix support for node 5.1.0 by updating plugman

lib/services/cordova-plugins.ts, lib/services/cordova-project-plugins-service.ts, test/plugins-service.ts
Currently plugin fetch is not working when marketplace plugin identifier is passed.
Also it does not work for org.apache.cordova.inappbrowser (looks like the id has been changed, but plugman search still finds the old id, while plugman fetch fails).
Fixes http://teampulse.telerik.com/view#item/306489
=> Allow plugin fetch by identifier

lib/services/livesync-service.ts
Result command file should be called `telerik.livesync.commands` instead of `temp.commands.file`
Ping @teobugslayer 
TP Reference: [[CLI][NativeScript] Fail to deploy/livesync to NS companion](http://teampulse.telerik.com/view#item/306613)
=> Fix livesync/deploy to NS companion

lib/appbuilder-cli.ts, package.json
Make shelljs opeartions silent
See https://github.com/NativeScript/nativescript-cli/issues/1247
=> Do not call adb kill-server on uninstall

lib/bootstrap.ts
`logger` has been required in common lib, but due to some Proton requirements, it should be required from each CLI.
Fix this by adding it to bootstrap and update to latest common lib.
=> Require logger and update to latest common lib

lib/services/cordova-project-plugins-service.ts, test/plugins-service.ts
When marketplace plugins and core plugins have same identifier, CLI does not work correctly.
Make sure to use the marketplace plugin whenever there's plugin with the same identifier in integrated plugins and in marketplace.
Make sure to remove all plugin instances when changing the version, for example if plugin is enabled from integrated plugins, and you try to update it, we will use the marketplace plugin.
So we will try to add new instance of the plugin in `.<config>.abproject`, for example:
Before:
```JSON
{
"CorePlugins": [ "com.telerik.feedback"]
}
```
After `appbuilder plugin add com.telerik.feedback` the file should be:
```JSON
{
"CorePlugins": [ "com.telerik.feedback@<selected_version>"]
}
```
More details for the issue - http://teampulse.telerik.com/view#item/307168
=> Make sure CLI works correctly with plugins

lib/commands/prop/prop-command-base.ts
In case user is using only lowercased values for properties, autocompletion is not working.
For example `appbuilder prop print core` is not autocompleted to coreplugins.
In fact the command will work with lowercased values, so enable using them.
Add lowercased values to the ones used for autocompletion.
With this change the above will work, but scenarios like `appbuilder prop print cOre` will not be autocompleted anyway.
Fixes http://teampulse.telerik.com/view#item/292405
=> Allow autocompletion of lowercased properties

lib/declarations.d.ts, lib/services/nativescript-project-plugins-service.ts
Allow usage of plugin variables of NativeScript plugins. Use `--var` option to pass values, for example:
`appbuilder plugin add plugin-var-plugin --var.APP_NAME test --var.FACEBOOK_APP_ID fb_appid`
For MarketPlace plugins we should use the Variables from Server, but currently it does not return correct info about them. So call registry.npmjs.org to get package.json and get variables info from there.
For plugins from npm, get the info from `registry.npmjs.org`
For local plugins get the info from its package.json.
For plugins passed as URLs get the info from the temp dir where it will be installed.
Use defaultValue specified in plugin for prompter's default value or when console is not interactive.
Implements http://teampulse.telerik.com/view#item/308123
=> Use plugin variables for NativeScript plugins

lib/commands/plugin/add-plugin.ts, lib/commands/plugin/list-plugin.ts, lib/declarations.d.ts, lib/services/cordova-project-plugins-service.ts, lib/services/nativescript-project-plugins-service.ts, lib/services/plugins-service.ts
Use the new `obsoletedIntegratedPlugins` object when:
* adding plugin - any integrated plugin that you try to add and has been obsoleted by marketplace plugin will be treated as its marketplace value. For example `appbuilder plugin add com.telerik.plugin.eqatecanalytics` will add `com.telerik.plugin.telerikanalytics` plugin.
* removing plugin - this operation will remove both plugins (in case somehow you have them) - the integrated one and its marketplace friend
* adding marketplace plugin - when adding marketplace plugin that obsoletes integrated plugin, the operation will remove the integrated one.
Add new method to pluginsService in order to filter obsoleted plugins when printing them.
Fix an issue in nativescipt-project-plugins-service where plugin's version is not printed correctly …
=> Use obsoletedIntegratedPlugins object from cordova.json

lib/hooks/typescript-compilation.ts, lib/project.ts
When for NS TypeScript project user had called `npm install`, there are `*.d.ts` files inside `node_modules`.
But we also have definition files in `typings` directory, so the compilation fails.
Fix this by skipping `node_modules` dir when checking for `.ts` files. We do not want to compile files from `node_modules` dir.
Also add check if `tsconfig.json` exists to use it and just spawn tsc as all user options specified in tsconfig.json MUST be respected.
Fixes http://teampulse.telerik.com/view#item/306751
=> Fix compilation of NS TypeScript projects

lib/services/cordova-project-plugins-service.ts, package.json
When we have obsoleted plugin with the same identifier as its marketplace replacement, current code filters it.
For example in case you add `com.telerik.feedback` and execute `appbuilder plugin`, it will not be listed.
Filter only items where the replacement id is not the same as integrated plugin's id.
=> Fix plugins list for obosleted plugins

test/deploy.ts
Update common-lib SHA to latest master where new tests for devicesService had been added.
Fix unit tests for `appbuilder deploy` (failing due to change of message in common-lib.
=> Add unit tests for devicesService

lib/services/nativescript-project-plugins-service.ts
Fix getting information for nativescript plugins, which do not have `repository` property in `package.json`.
Try adding `plugin-var-plugin` and executing `appbuilder plugin` after that. Error is raised because the plugin does not have repository property and we are trying to get repository.url.
No regression potential.
=> Fix getting information for some nativescript plugins

lib/declarations.d.ts, lib/plugins-data.ts, lib/project.ts, lib/project/cordova-project.ts, lib/project/framework-project-base.ts, lib/project/nativescript-project.ts, lib/project/project.d.ts, lib/services/cordova-project-plugins-service.ts, lib/services/nativescript-project-plugins-service.ts, test/project-properties-service.ts, test/stubs.ts
Print information about nativescript plugin variables.
Print the values when plugin is already added (`appbuilder plugin` command and when lisiting available plugins: `appbuilder plugin --available`).
Print plugins variables when listing available plugins (valid for Cordova and {N} Plugins) - even when plugin is not added, we know which are the required varialbes, show them to the user.
=> Print information about plugin variables

docs/man_pages/lib-management/plugin-add.md, docs/man_pages/lib-management/plugin-configure.md, docs/man_pages/lib-management/plugin.md
Fix the help for plugin commands in order to show that `plugin configure` works for NativeScript projects and you can use `--var` for NS Plugins.
=> Fix help for plugin commands

package.json
`appbuilder livesync --watch` fails with error when file is saved. The problem is in code used for NS CLI, which returns null instead of future.
=> Fix livesync --watch

test/resources/blank-Cordova.abproject
It is enabled by default in the new default Cordova version - 4.0.0
=> Set AndroidHardwareAcceleration to true

lib/project/cordova-project.ts, lib/project/framework-project-base.ts, lib/project/nativescript-project.ts, lib/project/project.d.ts
If `iOSDisplayName` is present but an empty string, then our current logic sets the `DisplayName` to `iOSDisplayName` and right after that decides that no `DisplayName` is present and uses a default one.
Fix the issue, by checking if a `DisplayName` is already set and then fork the logic between `iOSDisplayName` and the default one.
Ping @teobugslayer @rosen-vladimirov
=> Fix overwriting DisplayName when iOSDisplayName is present and empty

lib/project.ts, lib/project/cordova-project.ts, lib/project/nativescript-project.ts, lib/project/project-constants.ts, lib/project/project.d.ts, test/project-properties-service.ts, test/project.ts, test/stubs.ts
When `appbuilder init hybrid` is called, we should extract:
* `.abproject`
* `.debug.abproject`
* `.release.abproject`
* `.abignore`
* `cordova.ios.js`
* `cordova.android.js`
* `cordova.wp8.js`
When `appbuilder init native` is called, we should extract:
* `.abproject`
* `.abignore`
* `package.json`
In case any of them exists, we should not overwrite it.
Add new property to frameworkProject - `projectSpecificFiles` - it should define the required files that should exist after initialization.
Always extract all `*.abproject` and `*.abignore` files no matter of project type.
Add tests for the new functionality.
Introduce new project constant for `.abignore` file name.
Fixes http://teampulse.telerik.com/view#item/310769
=> Extract more files when initializing project

lib/providers/device-app-data-provider.ts
Remove unused property(servedApp) form iOSCompanion classes that breaks building for iOS companion apps.
http://teampulse.telerik.com/view#item/310864
=> Fix QR code generations for iOS Companion

lib/project.ts, lib/server-api.d.ts, lib/server-api.ts, lib/services/appmanager-service.ts, lib/services/appstore-service.ts, lib/swagger/service-contract-generator.ts
A minor bug inside our swagger did not allow for a clean api regeneration from endpoints containing multiple slashes (e.g. internal/apps/projects). Fix said bug and regenerate-api.
Api regeneration lead to some compilation issues - fix them by calling correct method overloads.
=> Regenerate server-api

lib/commands/build.ts, lib/commands/deploy.ts, lib/commands/emulate.ts, lib/commands/ensure-project-command.ts, lib/commands/live-sync.ts, lib/commands/livesync-cloud.ts
Created base ensure project command class to extract the common can execute method which checks if there is project when the command depends on project.
Refactored the other similar commands to remove the repeating can execute method.
=> Fixed bug in commands fail if executed outside project.

.vscode/launch.json, lib/services/cordova-project-plugins-service.ts
When the .debug.abproject and the .release.abproject files are deleted and then plugin is installed without specified configuration and the plugin variables are set in the .abproject file. When configuring the plugin variables for specific configuration the original plugin variables must be cloned because the changes must be saved in the configuration specific file only.
When getting the plugin variable from var option the configuration needs to be checked because if there is no specified configuration in the command it will be undefined.
Fixes http://teampulse.telerik.com/view#item/282804
=> Fix plugin configure command

lib/commands/framework-versions/print-versions.ts, lib/services/cordova-migration-service.ts
Add supported frameworks versions to the error message when using appbuilder mobileframework and the current version is not supported.
Fixes http://teampulse.telerik.com/view#item/312441
=> Fix framework not supported error message

lib/hooks/typescript-compilation.ts
When checking if command is executed in project in the typescript-compilation hook need to return not to throw error because the not in project message and command help will not be shown.
Fixes http://teampulse.telerik.com/view#item/308947
=> Fix bug in commands fail if executed outside project

postinstall.js
Fix LiveSync for iOS Simulator by changing:
* Root Project Path for NativeScript applications, which was incorrectly including "app" dir.
* Fix path where we copy files to be the iOS LiveSync Dir (/Library/Application Support/LiveSync) - for Cordova projects, the LiveSync plugin automatically gets all files from bundle to this directory, so next time when CLI livesyncs to simulator, we place the new files in the bundle. LiveSync plugin will not pull these changes in the LiveSync dir, so we have to do it manually.
Move LiveSync constants in the constants file.
**Regression potential:** None, changes are only in code used for iOS Simulator LiveSync. Currently it is not working, so we cannot break it more.
=> Fix LiveSync for iOS Simulator

lib/services/build.ts
Use correct LiveSync urls for Companion apps.
Pass App Identifier and configuration.
Fixes http://teampulse.telerik.com/view#item/313027
=> Fix LiveSync to Companion apps

lib/definitions/templates-service.d.ts, lib/project.ts, lib/project/cordova-project.ts, lib/project/nativescript-project.ts, lib/templates-service.ts, test/stubs.ts
In addition replace forgotten occurence of KendoUI.Empty instead of KendoUI.Blank in help.
Implemented with backwards compatibility `--template Blank` still works as expected.
Implements [Project templates should be JavaScript.Blank and TypeScript.Blank](http://teampulse.telerik.com/view#item/268482)
Ping @rosen-vladimirov and @TsvetanMilanov for code review
=> Rename `Blank` template name to `JavaScript.Blank`

lib/templates-service.ts
Currently post install fails as we are trying to call `.toLowerCase()` of undefined.
=> Fix post install

lib/config.ts, lib/project/cordova-project.ts, lib/project/nativescript-project.ts, lib/project/project.d.ts
Currently when deploying NativeScript apps on Android via Proton, we are unable to start the application, as we pass incorrect StartPackageActivity.
Fix this by extracting the correct names in constants. When deploy is called from Proton side, we'll set the correct name in the `$project`.
After that the execution of start method will use the value from `$staticConfig`. StaticConfig will return the value of project's property.
`deployOnDevices` method now has additional argument - framework. If it is passed and the provided value is NativeScript, we'll use the NativeScript's StartPackageActivity.
In all other cases we'll use Cordova's StartPackageActivity.
=> Allow starting of NativeScript apps on Android via Proton

lib/declarations.d.ts, lib/services/nativescript-migration-service.ts, lib/services/nativescript-project-plugins-service.ts
Since NativeScript version 1.5.2 is obsolete and it cannot be migrated to the old logic for migrating NativeScript projects is not needed any more.
Also the server returns NativeScript.json with additional property - obsoleteVersions and the property npmVersions is renamed to versions.
The improvement is described here http://teampulse.telerik.com/view#item/312022
=> Clean unused code for already deleted {N} versions

lib/qr.ts
When we try to generate QR Code for project with long name the library we use fails.
The QR Code generation logic was not compatible with the library and the exception that was thrown was not expected.
=> Fix QR Code generation for projects with long names

lib/declarations.d.ts, lib/services/nativescript-migration-service.ts, lib/services/nativescript-project-plugins-service.ts
The npmVersions property is removed, obsoleteVersions is renamed to deprecatedVersions.
=> Change the properties for NativeScriptMigrationData

lib/ionic-project-transformator.ts
When creating backup of the Ionic project and adding the Ionic_Backup folder to the .abignore file need to add EOL at the and of it.
=> Add EOL in .abignore file in Ionic projects

config/dependency-config.json
This reverts commit 96a22e645c6906f2a702e35da374d593cf4ceab6.
Will be introduced in AppBuilder's next release instead for more stability and time for testing
Ping @TsvetanMilanov
=> Downgrade Screen Builder to 0.0.12

lib/declarations.d.ts, lib/login.ts, lib/services/analytics-settings-service.ts
We are using incorrect property - id, now it's called uid. This leads to tracking all users with the same user id - "undefined".
Introduce interfaces for User and Tenant information.
=> Fix tracking of users

lib/commands/framework-versions/print-versions.ts, lib/commands/framework-versions/set-version.ts, lib/commands/project/create.ts, lib/commands/project/init.ts, lib/commands/prop/prop-print-android-version-code.ts, lib/commands/prop/prop-set-android-version-code.ts, lib/dynamic-help-provider.ts, lib/project.ts, lib/project/cordova-project.ts, lib/project/nativescript-project.ts, lib/project/resolvers/framework-project-resolver-base.ts, lib/project/resolvers/framework-project-resolver.ts, lib/project/resolvers/framework-simulator-service-resolver.ts, lib/providers/commands-service-provider.ts, lib/services/project-properties-service.ts, lib/services/samples-service.ts, test/build-configurations.ts, test/project.ts
Move TARGET_FRAMEWORK_IDENTIFIERS from $projectConstants (available in AppBuilder CLI only) to constants.
This way we can use it in common lib and all CLIs directly.
=> Move TARGET_FRAMEWORK_IDENTIFIERS to constants

lib/project.ts, lib/project/cordova-project.ts, lib/project/nativescript-project.ts
When executing appbuilder device run appid outside of project the CLI cannot determine which startPackageActivity name to use - for NativeScript or for Cordova application. The fix is to check where the command is executed and if it is not in project we need to run the adb command for both NativeScript and Cordova projects.
=> Fix device run command

lib/services/debug/darwin-debugger-service.ts
Rename packageId to appIdentifier in IAndroidApplicationInformation.
=> Rename packageId to appIdentifier

lib/project.ts
Instead of writing the whole project data to configuration files (.debug.abproject and .release.abproject), write only configuration-specific data.
Merge after https://github.com/telerik/mobile-cli-lib/pull/740
=> Write only configuration specific data to configuration files

lib/services/build.ts
When building NativeScript project we don't need to rely on configuration files existing.
=> Fix NativeScript build

lib/project.ts
Instead of caching the old keys, do a deep diff between configuration-specific data and current project data. Save only configuration-specific data to configuration files.
In addition, if no configuration is specified, set property in base configuration file (.abproject) and delete keys in the other configuration files (.debug.abproject, .release.abproject).
This is accomplished by setting the property of all configuration-specific data objects in addition to the project data object to the same value.
Ping @rosen-vladimirov and @TsvetanMilanov 
Merge after https://github.com/telerik/mobile-cli-lib/pull/742 (although this PR doesn't depend on it)
=> Remove logic about storing configuration-specific keys

lib/services/livesync/livesync-service.ts
When checking if the livesync is supported and the application is not installed the result is false and we need to deploy the application on the device and check again.
=> Check if livesync is supported

lib/declarations.d.ts, lib/project.ts, lib/project/cordova-project.ts, lib/project/framework-project-base.ts, lib/project/nativescript-project.ts, lib/project/project.d.ts, lib/resource-downloader.ts, lib/services/cordova-migration-service.ts, lib/services/nativescript-migration-service.ts, test/project-properties-service.ts, test/stubs.ts
When we integrate experimental version of NativeScript we need to upload new package of the CLI in npm with the updated nativeScript-migration-data.json file so the users can use the new version.
It will be better to download the nativeScript-migration-data.json file when NativeScript related command is executed.
=> Download nativeScript-migration-data.json file

lib/bootstrap.ts, lib/services/analytics-service.ts, test/resources/blank-NativeScript.abproject
We need to redirect the analytics data sent from Sublime to separate analytics project so we can keep track of how many users are using Telerik AppBuilder for Sublime Text.
=> Add analytics for Sublime

lib/services/build.ts
Whenever running build/deploy without specifying any configuration default to the first (alphabetically sorted) configuration that the user has. If no configurations are present still default to debug though
Re-targeted from https://github.com/Icenium/icenium-cli/pull/1474
=> Default to first configuration

lib/declarations.d.ts, lib/services/plugins/cordova-project-plugins-service.ts, lib/services/plugins/nativescript-project-plugins-service.ts, lib/services/plugins/npm-plugins-service-base.ts
When the user tries to fetch plugin from the plugins directory in the project we do not need to copy again the already existing plugin.
=> Fix plugin fetch from plugins directory

docs/man_pages/index.md
Fixes [[CLI] Some ScreenBuilder commands are missing on the start page of html help](http://teampulse.telerik.com/view#item/318007)
Ping @TsvetanMilanov or @rosen-vladimirov for a quick glance
=> Add new SB commands in starting help page

package.json
Update osenv dependency in order to resolve issue on Mac OS X and Linux when HOME environment variable is not set.
=> Update osenv dependency

lib/declarations.d.ts, lib/services/plugins/cordova-project-plugins-service.ts, lib/services/plugins/nativescript-project-plugins-service.ts, lib/services/plugins/npm-plugins-service-base.ts, test/plugins-service.ts
When existing plugin name is passed to the fetch command it takes very long time to fetch the plugin. Slow fetch is expected only when keywords are passed to the fetch command. We can send request to http://registry.npmjs.org/[plugin-name] and see if there is registered plugin before using the slow npm find command.
=> Search http://registry.npmjs.org for plugins

lib/services/plugins/nativescript-project-plugins-service.ts, lib/services/plugins/npm-plugins-service-base.ts
Wehn we install the plugin with npm to Temp directory we need to check if the plugin is installed in node_modules in the Temp folder both for NativeScript and for Cordova projects.
=> Fix failing plugin fetch tests

lib/helpers.ts, lib/services/user-settings-service.ts, package.json
Using this dependency leads to the error `breaker is not defined` when working with iOS devices and installing dependencies with npm 3.
As the logic is somewhat tirvial remove said dependency and implement the code.
=> Remove string-to-json dependency

lib/project.ts, lib/project/project.d.ts, lib/services/plugins/cordova-project-plugins-service.ts, lib/services/project-properties-service.ts, test/plugins-service.ts
- Fix `$ appbuilder prop set CorePlugins <values> --debug` not setting values to specific configuration.
- Fix `$ appbuilder plugin add console --release` not moving all CorePlugins to all available configurations.
- Fix possible adding of multiple plugins with same name in a single configuration (missing `uniq` in the code).
When change in CorePlugins is applied, save all possible .abproject files as all of them might be affected.
Extract the `updateProjectProperty` functionality from `updateProjectPropertyAndSave` method to a separate public method in order to keep the current logging for `plugin add` command.
Fixes http://teampulse.telerik.com/view#item/317915
=> Fix adding CorePlugins to specific configuration

lib/commands/debug.ts, lib/declarations.d.ts, lib/services/debug/darwin-debugger-service.ts
Pass framework as required by new API in common lib when mapping abstract to TCP port.
=> Update to latest common lib API for mapAbstractToTcpPort

Gruntfile.js, lib/services/cordova-migration-service.ts, publish.cmd
Fix publishing of the CLI as currently the published package does not have it's scripts section. The reason is that we pass `--ignore-scripts` to `npm publish` command. This removes all scripts from the published package.
After removing `--ignore-scripts` it turned out the package cannot be published. The problem is that when `npm publish <tgz>` is used, the package is added to local npm cache. After that it's package.json is extracted from the cached .tgz file and modified with additional metadata. At this point npm calls the prepublish script, but it fails to find our prepublish.js as it's not extracted in the cache (only the package.json is extracted).
So in order to fix this, remove the `prepublish` script in the `grunt pack` step.
I've not removed the prepublish script from the …
=> Fix publish of the CLI

lib/declarations.d.ts, lib/services/build.ts, lib/services/livesync/livesync-service.ts, test/deploy.ts
If we want to download the build results directly from s3 we need to send one additional property in the request - AcceptResults, with value - Url;LocalPath. In the response the link to the result will be in the FullPath property and the Format will be Url. In case we can't download the build results from s3 (wp8) we need to use the LocalPath method.
=> Download build results from s3

Gruntfile.js, README.md, lib/services/cordova-migration-service.ts, package.json, publish.cmd
Cherry pick fixes:
**Fix publish of the CLI**
Fix publishing of the CLI as currently the published package does not have it's scripts section. The reason is that we pass `--ignore-scripts` to `npm publish` command. This removes all scripts from the published package.
After removing `--ignore-scripts` it turned out the package cannot be published. The problem is that when `npm publish <tgz>` is used, the package is added to local npm cache. After that it's package.json is extracted from the cached .tgz file and modified with additional metadata. At this point npm calls the prepublish script, but it fails to find our prepublish.js as it's not extracted in the cache (only the package.json is extracted).
So in order to fix this, remove the `prepublish` script in the `grunt pack` step.
I've …
=> Cherry pick fixes and bump version

lib/bootstrap.ts, lib/declarations.d.ts, lib/hooks/typescript-compilation.ts, lib/options.ts, lib/services/build.ts, lib/services/nativescript-migration-service.ts, lib/services/platform-migration.ts, lib/services/plugins/nativescript-project-plugins-service.ts, lib/services/project-migration-service.ts, lib/services/simulator-service.ts, test/plugins-service.ts, test/simulator-service.ts
Add support for installing npm dependencies. Provide two methods for public API:
- install - installs everything from package.json. In case a specific dependency must be installed, it's described as second argument with its name, version and should `@types` be installed.
- uninstall - uninstalls the specified dependency from both node_modules and package.json. The call will also remove `@types/<dependency>` entry from devDependencies.
On each build related command in NativeScript TypeScript project, CLI will call `npm install` in order to verify all required dependencies are installed.
On plugin add - try adding `@types/<dependency>` in case it exists and `--no-types` is not passed on the terminal.
On plugin remove - remove both the dependency and `@types/<dependency>` entries. …
=> Add support for installing npm modules and @types

lib/commands/debug.ts, lib/commands/deploy.ts, lib/commands/emulate.ts, lib/declarations.d.ts, lib/providers/livesync-provider.ts, lib/services/build.ts, lib/services/livesync/livesync-service.ts
Since the app identifier can be changed in AndroidManifest.xml and config.xml the server needs to return the identifier which is used to build the application. That's why we need to use the app identifier from the server instead of the one from the .abproject.
=> Start App with identifier returned from the server

lib/commands/debug.ts, lib/commands/deploy.ts, lib/commands/emulate.ts, lib/declarations.d.ts, lib/providers/livesync-provider.ts, lib/services/build.ts, lib/services/livesync/livesync-service.ts, package.json
Cherry-pick the following commits from master:
Since the app identifier can be changed in AndroidManifest.xml and config.xml the server needs to return the identifier which is used to build the application. That's why we need to use the app identifier from the server instead of the one from the .abproject.
We need to get the correct app id which will be used to build the application on our server when we execute operations for Android.
=> Get the correct app id

lib/services/plugins/npm-plugins-service-base.ts
When we try to fetch plugin for Cordova project from github we should not treat it as local plugin.
=> Fix pathToPlugin.indexOf is not a function

lib/hooks/before-build.js, lib/hooks/before-deploy.js, lib/hooks/before-livesync.js, lib/hooks/typescript-compilation.ts, package.json
Previously there were some cases when TypeScript was unable to generate .js files. After adding the `noEmitOnError` parameter to tsconfig, TypeScript will not generate .js files ONLY when it is set to true.
Currently our TypeScriptService does not handle this case as it thinks that the .js files are not generated in some cases. Respect the parameter and always show the output of the compiler to the user.
Also make sure all of our hooks are executed in the current process, so the error messages from them will be correctly shown to the user. This requires adding `esprima` as dependency as its used in mobile-cli-lib code.
=> Support noEmitOnError parameter and execute hooks in process

lib/declarations.d.ts, lib/services/plugins/cordova-project-plugins-service.ts, lib/services/plugins/nativescript-project-plugins-service.ts, lib/services/plugins/plugins-service-base.ts, test/plugins-service.ts, test/stubs.ts
When we fetch scoped dependencies we need to get the correct directory in which the dependency is installed because it will be in `node_modules/@<scope>/<dependency>` instead of `node_modules/<dependency>`.
=> Fix add and fetch scoped dependencies

lib/constants.ts, lib/server-api.d.ts, lib/server-api.ts, lib/services/appmanager-service.ts, lib/services/appstore-service.ts, lib/services/remote-projects-service.ts, lib/services/user-settings-service.ts
Regenerate server api and fix all compilation errors:
* Use endpoint to upload package from URI when performing `appmanager upload`
* Use endpoint to upload package from URI when performing `appstore upload`
* Skip passing `checkUpgradability` argument which is no longer supported when calling `getApplication`
* Extract constants file for storing AppBuilder related constants
* Pass `user-settings.xml` as file name when getting or saving user settings
TP Ref: [Cannot publish to AppManager](http://teampulse.telerik.com/view#item/320571)
=> Regenerate server api

lib/project.ts, lib/project/project.d.ts, lib/services/appmanager-service.ts, lib/services/appstore-service.ts
Expose a way to default to a desired configuration (if present among the user configurations) throught the `$project` dependency.
Set project configuration as:
* What the user has defined as `--config`
* `release` (if present among the user's configurations)
* The lexicographically first configuration the user has
* `Debug`
In that order.
Mind that this is a project configuration as opposed to build configuration and even in the unlikely case that we end up building in `Debug`, the build configuration will always be `release` thus preventing any unwanted behavior.
Fixes [appmanager and appstore upload do not respect --config ](http://teampulse.telerik.com/view#item/318698)
=> Respect configurations on appmanager/appstore upload

lib/project.ts, lib/project/cordova-project.ts, lib/project/framework-project-base.ts, lib/project/nativescript-project.ts, lib/project/project.d.ts, lib/services/build.ts, test/nativescript-project.ts, test/project-properties-service.ts, test/project.ts, test/stubs.ts
When we create NS TS project we need to install all npm dependencies because if we don't have the tns-core-modules installed we will not add theirs .d.ts in .abreferences file untill the project is built.
Also we need to install the dependencies on every project related command because we must be sure that we are working with correct content of node_modules.
=> Install all npm dependencies in NS TS projects

lib/config.ts, test/project-properties-service.ts, test/stubs.ts
Use the monkey tool to start Android applications on device. This way we do not have to care about the startPackageActivity name and we can start the application in case a custom activity is used.
Remove unused code and variables.
=> Use monkey to start Android applications

lib/project/cordova-project.ts
Before build CLI tries to ensure all `cordova.<platform>.js` files are part of the project.
When any of them is missing, CLI should extract it from the resources and add it to the project. Instead of adding it, CLI fails with error:
`Error: ENOENT: no such file or directory, open '<project dir>\cordova.<platform>.js'`
The reason is incorrect code in CLI that tries to verify if the content of the file in the project (no matter that it does not exist) is the same as the one in the resources of CLI.
Fixes http://teampulse.telerik.com/view#item/321100
=> Fix adding missing cordova.<platform>.js file to project

lib/services/project-migration-service.ts
When we migrate TS project and we remove the tns-core-modules we use the shelljs to remove the directory but there is some bug when using it - it fails to delete some of the subdirecotries. Thet's why we will use rimraf instead of shelljs.
=> Use rimraf to remove tns-core-modules

lib/declarations.d.ts, lib/services/build.ts
When we generate QR codes for iOS we need to pass the correct download path when we call the server endpoint for livesync url generation and also we need to pass the project configuration because the endpoint needs it.
Fixes http://teampulse.telerik.com/view#item/321268
=> Fix iOS QR code generation

lib/services/plugins/plugins-service-base.ts, test/stubs.ts
When we fetch plugin we are using npm install <plugin-name> and npm also installs the dependencies of the plugin. Since we do not need them we should delete them.
=> Delete node_modules of fetched plugin

lib/commands/live-sync.ts
When we execute livesync on iOS simulator we need to set the justlaunch option to true if there is no watch flag because if we don't set it the command will not release the console.
=> Set justlaunch flag when executing livesync

lib/commands/deploy.ts
When we have multiple devices connected and a device related command is executed we should build the project only once instead of building for each device.
=> Fix the multiple builds

lib/services/plugins/cordova-project-plugins-service.ts, test/plugins-service.ts
When we fetch plugin in Cordova project we must not add it to the core plugins because when we build the project the build will fail for duplicate symbols/classes.
Fixes http://teampulse.telerik.com/view#item/321807
=> Do not add fetched plugin to core plugins

docs/man_pages/lib-management/plugin-add.md, lib/services/project-migration-service.ts
Document `--no-types` option, which is used to disable installation of `.d.ts` files in NativeScript TypeScript projects.
=> Document `--no-types` option

lib/service-util.ts, test/service-util.ts
Use npm proxy for connections to registry.npmjs.org. This way in case the user has set a proxy, we'll use it.
Also respect user's settings for npm registry.
http://teampulse.telerik.com/view#item/322319
=> Respect npm settings - proxy and registry 

lib/commands/web-view/set-web-view.ts, lib/declarations.d.ts, lib/services/cordova-migration-service.ts, lib/services/web-view-service.ts, test/project.ts
Since there is an issue with our WKWebView for Cordova projects with version >=5.0.0 we need to use the WKWebView Engine from Cordova for those projects. When we set the webview we need to check the framework version and choose the correct WKWebView. Also when we migrate the project we should change the WKWebView.
Fixes: http://teampulse.telerik.com/view#item/321628
=> Use WKWebView Engine for Cordova >=5.0.0

lib/service-util.ts
When we make a call to registry.npmjs.org in order to get the latest version of AppBuilder CLI, we set a timeout of 6000ms.
If the call hangs, we throw error of the newly created FiberFuture and expect to catch it after that.
This works fine, however the FiberFuture is not removed from the cache with futures. Before exiting our process we have a check for "futures left behind". The FiberFuture is still in the cache of "not resolved" ones and we show error:
```
Error: There are outstanding futures. Construction call stacks:
....
```
This is a problem with the FiberFuture construction that cannot be resolved easily. However it's not reproducible in case we use a pure Future. So move the timeout option directly to the httpRequest call where we use Future, not FiberFuture.
The fix includes …
=> Prevent outstanding futures when npm hangs

lib/project.ts
The ionic project configuration file is renamed from ionic.project to ionic.config.json. When we determine the type of the project in the check for ionic project we must check for both the old and the new file name.
=> Fix is ionic project check

test/stubs.ts
When we validate the hook arguments we try to resolve all of them but there is one argument which is not registered in the injector - hookArgs. If some hook wants to use it we will try to resolve it and fail. The solution is to skip the validation for the hookArgs argument.
=> Do not try to resolve hookArgs

package.json
iOS Simulator device logs are printed directly to process.stdout from the ios-sim-portable. However this makes it really difficult to filter the logs and provide them to different callers (for example AppBuilder CLI, NativeScript CLI, Proton).
In order to fix this, use the ios-sim-portable just to start the process of getting device logs. Filter them in the CLI itself.
Also change the logic in ios-log-filter to use process pid in case it's passed. For iOS Simulator we have filtered logs based on the PID of the application. With these changes, simulator logs are passed to ios-log-filter, so that's why we need process' PID there.
When application is restarted (during livesync for example), we set the PID again and the filter will use the new PID.
Merger ONLY AFTER updating ios-sim-portable …
=> Fix getting ios simulator device logs

.gitmodules
We should use https instead of ssh for the mobile-cli-lib.
=> Change the submodule url to https

package.json
The validation of -- options passed on the command line depends on yargs module. Update it to latest versions as the previously used one didn't set correct values of options marked as strings.
Also in our code we pass object of valid options to yargs. Options which have `-` in the name are treated in a special manner in yargs. However instead of passing them with `-`, we pass their secondary representation (remove the `-` and capitalize the next letter).
This way, when the user passes option with `-`, yargs treat it with it's default behavior and does not respect our options for it (as we have not defined that we have option with `-`).
Example:
```JavaScript
var yargs = require("yargs");
var opts = {
"profile-dir": { type: "string" }
};
console.log(yargs(process.argv).options(opts).argv); …
```
=> Fix validation of -- options

lib/services/remote-service.ts
Add client to simulator name mapping for Xcode 8.
Also we must get appId from the request for users with Xcode 7+ in order to run the application on the iOS simulator.
=> Fix remote command

lib/services/plugins/cordova-project-plugins-service.ts
Since there is some change in the npmjs search our current way of searching for plugins is broken. The problem is that now the order of the keywords in the search does matter.
For example if we search for "ecosystem:cordova console" we won't find any plugins but if we search for "console ecosystem:cordova" we will find the plugins that we are looking for.
Approved in https://github.com/Icenium/icenium-cli/pull/1590
=> Fix Cordova plugins search

lib/services/plugins/nativescript-project-plugins-service.ts
Fix code that verifies if NativeScript plugin can be used in the project. Each nativescript plugin may describe the minimum required version of the framework. Our check is not correct and it does not allow adding of nativescript-plugin-livepatch plugin (it's required versions are 1.x.x).
Fix the check - now if all versions described in plugin's package.json are greater than current framework version, the plugin will not be added. In case at least one of the version described in plugin's package.json is compatible with our FrameworkVersion in .abproject, the plugin will be added.
=> Fix adding of NativeScript plugins

lib/services/analytics-service.ts
* Instead of using the application's own appid we should use the companion app's appid when performing LiveSync for the companion
* Fix compile error in analytics-service
* Update submodule to latest SHA
=> Update submodule to latest SHA

Gruntfile.js
Specifies all dependencies as bundled before executing `grunt pack`.
This way the `.tgz` produced contains the code along with the dependencies
=> Add bundle-pack grunt task

bin/appbuilder.js, lib/appbuilder-cli.ts
As old versions of Node.js cannot be used anymore (after transpiling to ES6), we should break the process when such case happens.
Use only var instead of let, const, as only var keyword is supported in Node.js 0.10.x
=> Break CLI process when Node is not supported

lib/services/plugins/nativescript-project-plugins-service.ts
We need to cache the result of the decorated methods for each instance not for all instances. Also we need to add the name of the cached member to the cache property becasue if we do not add it we can't cache other members.
Also we need to execute build and deploy on multiple devices synchronously because the build will fail if the actions are executed for each device in parallel.
There were forgotten console.logs from debugging which are removed.
Common lib reference: https://github.com/telerik/mobile-cli-lib/pull/873
=> Fix cache decorator

package.json
`deviceProjectRootPath` had been renamed to `getDeviceProjectRootPath` in one of previous commits. It's been fixed in the base class, but the classes that extend the base class were still using the old name.
Rename the method everywhere.
Fix `unable to resolve callstack error`
When an error is raised we are trying to resolve the callstack, but there's no source map for TypeScript generated methods for `async` (`__awaiter`). This breaks our logic. In such case just print the line in `.js` instead of `.ts` file.
Remove `source-map.js` from `vendor` and use the npm package.
=> Fix livesync errors

lib/commands/ensure-project-command.ts, lib/commands/kendoui-base.ts, lib/definitions/express.d.ts, lib/helpers.ts, package.json, test/project.ts, test/stubs.ts, test/test-bootstrap.ts
Currently we are using `node.d.ts` from version `0.11.x`. In order to get latest updates, remove our own version of node.d.ts and use the one from `@types`. Use the version for Node 6.
Fix code according to new definitions. Introduce ICliGlobal interface in order to describe the global object that's used from CLI (we add some properties to the global object).
Add definition file for `xmlhttprequest` module.
Add definitions for Eqatec Analytics.
Modify `ws.d.ts` according to latest changes.
=> Use node.d.ts from @types

lib/project/cordova-project.ts, lib/project/framework-project-base.ts, lib/project/nativescript-project.ts
We do not need to add .png asset when the project has the 9 patch png version of this asset.
Common lib reference: https://github.com/telerik/mobile-cli-lib/pull/884
TP reference: http://teampulse.telerik.com/view#item/328196
=> Fix ensure all platform assets

bin/appbuilder.cmd, bin/appbuilder.js
At the moment when you have CLI 3.6.x (from UAT or Live) and you try installing version from master (SIT), installation fails with:
```
npm ERR! Refusing to delete /usr/local/nvm/versions/node/v7.0.0/bin/appbuilder: ../lib/node_modules/appbuilder/bin/appbuilder.js symlink target is not controlled by npm /usr/local/nvm/versions/node/v7.0.0
npm ERR! File exists: /usr/local/nvm/versions/node/v7.0.0/bin/appbuilder
npm ERR! Move it away, and try again.
```
The problem is that in master branch we've tried to simplify the files that we have in CLI's bin dir.
However `npm` acts a little bit strange to these changes. In UAT and Live versions, when CLI is installed globally, npm makes symlink to CLI's `bin/appbuilder.js` file. We've removed this file, and in version from master the symlink should …
=> Fix upgrade of CLI

lib/services/appmanager-service.ts
For automation purposes we should not open AppManager URL in the browser.
This will allow users to automate commands like `$ appbuilder appmanager upload <platform>`
and `$ appbuilder appmanager livesync <platform>`
So in case `--skipUi` is passed to these commands, all actions will be executed, but the last step (opening the URL in browser) will not be executed.
=> Do not open AppManager URL in browser when --skipUi is passed

lib/services/cordova-migration-service.ts, lib/services/kendoui-service.ts
During migration from fibers to promises, we've lost one `!` in the check if npm package has typings in `@types` repo.
This led to incorrect behavior:
- typings of packages, which are available in `@types`, are not installed (for example `lodash`).
- trying to install plugin, which does not have typing in `@types` leads to error (something like `Error while installing dependency: Command npm.cmd failed with exit code 4294963238.`).
Fix the check (add the missing `!`) which will fix the incorrect behavior.
=> Fix check if package has `@types`

README.md, lib/services/nativescript-migration-service.ts, package.json
Currently building the package fails when CLI tries to download `https://<environment>/appbuilder/Resources/NativeScript/tns_modules/TS/2.5.0tns-core-modules.zip`
As we are now using tns-core-modules 2.5.1 the zip name that CLI tries to download is incorrect (should be 2.5.1). This leads to error, so other resources AFTER this one are not downloaded.
So the produced package is not correct.
As these zip files had been used in older CLI versions, skip their download. They have been required when we've been using local `.d.ts` files for `tns-core-modules`. Now we rely on the `.d.ts` files in the npm package, so no need ot include any of the `.zip` files in CLI.
=> Fix building of the package 

tsconfig.json
When Node.js 4 is used, CLI hangs when iOS device is detected. There are two problems:
- an error is raised in our deviceNotificationCallback. This error is not propagated by ffi back to us, so the process waits for calling a callback that will never be called as we've already thrown exception. This behavior will be fixed when we remove ffi and ref as dependencies.
- The raised error is: `[SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode]`. With Node.js 4.x.x, when you use "const" or "let" in the code, you have to place "use strict" at the top of the `.js` file. This is done by TypeScript itself during transpilation. However not in all cases. For some files, TypeScript decides to omit this "use strict". This way when we require any …
=> Fix iOS device detection with Node.js 4

lib/services/plugins/cordova-project-plugins-service.ts, lib/services/plugins/nativescript-project-plugins-service.ts, lib/services/web-view-service.ts
When a plugin has variables that has to be set, CLI checks the command line and in case the `--var` option is not passed, a prompt is shown to the user to enter a value.
At the moment this is broken as we are prompting in parallel promises. This leads to several issues - user is not able to enter values for the variables and also a memory leak warning is shown.
Fix the execution to be sync.
Bug is reproducible for both Cordova and NativeScript projects.
=> Fix prompting for plugin variables

lib/services/plugins/cordova-project-plugins-service.ts
When try to fetch plugin and the plugin doesn't have a description or name,
appbuilder-cli throw error `Cannot read property '$t' of undefined`.
Fix: [#329398](http://teampulse.telerik.com/view#item/329398)
=> Fix installation of plugins without description.

package.json, test/resources/blank-Cordova.abproject
Also update `grunt-shell` as the old version fails to run the tests with `maxbuffer exceeded`.
=> Fix expected Cordova version in tests to 6.4.0

lib/project/nativescript-project.ts, test/stubs.ts
Try-catch the whole thing.
Also replace shelljs.touch with a simple set of atime/ctime/mtime. This is done because shelljs.touch process.exits in case of a locked file or whatnot.
Merge after https://github.com/telerik/mobile-cli-lib/pull/946
Fixes [Incorrect failure upon inability to download nativeScript-migration-data.json from server](http://teampulse.telerik.com/view#item/344124)
=> Do not throw upon failure to get nativeScriptMigrationFileName

lib/services/remote-projects-service.ts
Add missing await - else `cloud export` fails because we try to unzip before downloading
Ping @rosen-vladimirov 
TP: [[CLI] Cloud export command fails](http://teampulse.telerik.com/view#item/344205)
=> Cloud export missing await

bin/appbuilder, package.json
Deprecate the support for Node.js 4 and 5 - on each CLI command, users who use any version starting with 4.x or 5.x will see warning.
Add full support for Node.js - currently we have warning that support for Node.js 8.x.x is not verified - add the 8.x.x versions in package.json as verified.
=> Deprecate Node.js 4 and 5, full support for Node.js 8

.travis.yml, docs/man_pages/project/creation/create-screenbuilder.md, docs/man_pages/project/creation/create.md, docs/man_pages/screenbuilder/add-about.md, docs/man_pages/screenbuilder/add-authentication.md, docs/man_pages/screenbuilder/add-dataprovider.md, docs/man_pages/screenbuilder/add-field.md, docs/man_pages/screenbuilder/add-form.md, docs/man_pages/screenbuilder/add-list.md, docs/man_pages/screenbuilder/add-view.md, docs/man_pages/screenbuilder/screenbuilder.md, docs/man_pages/screenbuilder/upgrade-screenbuilder.md, lib/commands/project/create.ts, lib/commands/screenbuilder.ts, lib/declarations.d.ts, lib/services/screen-builder-service.ts, test/help.ts
ScreenBuilder commands can work with Node.js 4, but not with newer Node.js versions.
As we deprecate support for Node.js 4, deprecate the screenbuilder related commands as well and inform the user that we'll delete them in the next official release.
=> Deprecate all ScreenBuilder commands

lib/project.ts
At the moment, when `--debug` option is passed and there's no `.debug.abproject` in the project, CLI fails with error:
```
Operation cannot be completed because configurations Debug are invalid.
```
In the previous versions of CLI, we have been creating the file manually and the operation continues.
The new behavior is introduced with a change in `mobile-cli-lib` (https://github.com/telerik/mobile-cli-lib/pull/970)  where it has been causing other issues.
Return the old behavior only for AppBuilder CLI by placing the deleted code in its source. Add check if `projectDir` is set, so the creation of project (which also uses the same code) will not fail.
=> Fix passing `--debug`(`--release`) when there's no such build config

docs/man_pages/index.md, docs/man_pages/project/creation/cloud-export.md, docs/man_pages/project/creation/cloud.md, docs/man_pages/project/creation/create-hybrid.md, docs/man_pages/project/creation/create-native.md, docs/man_pages/project/creation/create-screenbuilder.md, docs/man_pages/project/creation/create.md, docs/man_pages/project/creation/export.md, docs/man_pages/project/creation/init-hybrid.md, docs/man_pages/project/creation/init-native.md, docs/man_pages/project/creation/init.md, docs/man_pages/project/creation/sample-clone.md, docs/man_pages/project/creation/sample-hybrid.md, docs/man_pages/project/creation/sample-native.md, lib/bootstrap.ts, lib/commands/cloud-projects.ts, lib/constants.ts, lib/declarations.d.ts, lib/server-api.d.ts, lib/server-api.ts, lib/service-util.ts, lib/services/cloud-projects-service.ts, test/cloud-projects.ts
Introduce `$ appbuilder export` command, which enables exporting a project for development with Cordova/NativeScript CLI.
Ping @rosen-vladimirov @nadyaA @TomaNikolov
=> Introduce export command
